#!/usr/bin/env bash

source="${BASH_SOURCE[0]}"
while [ -h "$source" ] ; do
    prev_source="$source"
    source="$(readlink "$source")";
    if [[ "$source" != /* ]]; then
        # if the link was relative, it was relative to where it came from
        dir="$( cd -P "$( dirname "$prev_source" )" && pwd )"
        source="$dir/$source"
    fi
done
bin_dir="$( cd -P "$( dirname "$source" )" && pwd )"

# Set inital heap size
extra_args=("--vm.Xms512M")
# Increase stack size
extra_args+=("--vm.Xss16M")

# Default to polyglot launcher in JVM mode
extra_args+=("--jvm" "--polyglot")
# Make ReflectionUtils work
extra_args+=("--vm.-add-exports=java.base/jdk.internal.module=ALL-UNNAMED")

if [[ "$(uname -s)" == "Darwin" ]]; then
    extra_args+=("--vm.Xdock:name=TruffleSqueak")
fi

exec "${bin_dir}/trufflesqueak-launcher" "${extra_args[@]}" "$@"
