// Generated by jextract

package de.hpi.swa.trufflesqueak.shared.sdl.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int __nranges;
 *     _RuneEntry *__ranges;
 * }
 * }
 */
public class _RuneRange {

    _RuneRange() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_INT.withName("__nranges"),
        MemoryLayout.paddingLayout(4),
        SDL_h.C_POINTER.withName("__ranges")
    ).withName("$anon$70:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt __nranges$LAYOUT = (OfInt)$LAYOUT.select(groupElement("__nranges"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int __nranges
     * }
     */
    public static final OfInt __nranges$layout() {
        return __nranges$LAYOUT;
    }

    private static final long __nranges$OFFSET = $LAYOUT.byteOffset(groupElement("__nranges"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int __nranges
     * }
     */
    public static final long __nranges$offset() {
        return __nranges$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int __nranges
     * }
     */
    public static int __nranges(MemorySegment struct) {
        return struct.get(__nranges$LAYOUT, __nranges$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int __nranges
     * }
     */
    public static void __nranges(MemorySegment struct, int fieldValue) {
        struct.set(__nranges$LAYOUT, __nranges$OFFSET, fieldValue);
    }

    private static final AddressLayout __ranges$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("__ranges"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _RuneEntry *__ranges
     * }
     */
    public static final AddressLayout __ranges$layout() {
        return __ranges$LAYOUT;
    }

    private static final long __ranges$OFFSET = $LAYOUT.byteOffset(groupElement("__ranges"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _RuneEntry *__ranges
     * }
     */
    public static final long __ranges$offset() {
        return __ranges$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _RuneEntry *__ranges
     * }
     */
    public static MemorySegment __ranges(MemorySegment struct) {
        return struct.get(__ranges$LAYOUT, __ranges$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _RuneEntry *__ranges
     * }
     */
    public static void __ranges(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(__ranges$LAYOUT, __ranges$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

