// Generated by jextract

package de.hpi.swa.trufflesqueak.shared.sdl.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_HapticDirection {
 *     SDL_HapticDirectionType type;
 *     Sint32 dir[3];
 * }
 * }
 */
public class SDL_HapticDirection {

    SDL_HapticDirection() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_CHAR.withName("type"),
        MemoryLayout.paddingLayout(3),
        MemoryLayout.sequenceLayout(3, SDL_h.C_INT).withName("dir")
    ).withName("SDL_HapticDirection");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte type$LAYOUT = (OfByte)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_HapticDirectionType type
     * }
     */
    public static final OfByte type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_HapticDirectionType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_HapticDirectionType type
     * }
     */
    public static byte type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_HapticDirectionType type
     * }
     */
    public static void type(MemorySegment struct, byte fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final SequenceLayout dir$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("dir"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Sint32 dir[3]
     * }
     */
    public static final SequenceLayout dir$layout() {
        return dir$LAYOUT;
    }

    private static final long dir$OFFSET = $LAYOUT.byteOffset(groupElement("dir"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Sint32 dir[3]
     * }
     */
    public static final long dir$offset() {
        return dir$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Sint32 dir[3]
     * }
     */
    public static MemorySegment dir(MemorySegment struct) {
        return struct.asSlice(dir$OFFSET, dir$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Sint32 dir[3]
     * }
     */
    public static void dir(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, dir$OFFSET, dir$LAYOUT.byteSize());
    }

    private static long[] dir$DIMS = { 3 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * Sint32 dir[3]
     * }
     */
    public static long[] dir$dimensions() {
        return dir$DIMS;
    }
    private static final VarHandle dir$ELEM_HANDLE = dir$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * Sint32 dir[3]
     * }
     */
    public static int dir(MemorySegment struct, long index0) {
        return (int)dir$ELEM_HANDLE.get(struct, dir$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * Sint32 dir[3]
     * }
     */
    public static void dir(MemorySegment struct, long index0, int fieldValue) {
        dir$ELEM_HANDLE.set(struct, dir$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

