// Generated by jextract

package de.hpi.swa.trufflesqueak.shared.sdl.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_DateTime {
 *     int year;
 *     int month;
 *     int day;
 *     int hour;
 *     int minute;
 *     int second;
 *     int nanosecond;
 *     int day_of_week;
 *     int utc_offset;
 * }
 * }
 */
public class SDL_DateTime {

    SDL_DateTime() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_INT.withName("year"),
        SDL_h.C_INT.withName("month"),
        SDL_h.C_INT.withName("day"),
        SDL_h.C_INT.withName("hour"),
        SDL_h.C_INT.withName("minute"),
        SDL_h.C_INT.withName("second"),
        SDL_h.C_INT.withName("nanosecond"),
        SDL_h.C_INT.withName("day_of_week"),
        SDL_h.C_INT.withName("utc_offset")
    ).withName("SDL_DateTime");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt year$LAYOUT = (OfInt)$LAYOUT.select(groupElement("year"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int year
     * }
     */
    public static final OfInt year$layout() {
        return year$LAYOUT;
    }

    private static final long year$OFFSET = $LAYOUT.byteOffset(groupElement("year"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int year
     * }
     */
    public static final long year$offset() {
        return year$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int year
     * }
     */
    public static int year(MemorySegment struct) {
        return struct.get(year$LAYOUT, year$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int year
     * }
     */
    public static void year(MemorySegment struct, int fieldValue) {
        struct.set(year$LAYOUT, year$OFFSET, fieldValue);
    }

    private static final OfInt month$LAYOUT = (OfInt)$LAYOUT.select(groupElement("month"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int month
     * }
     */
    public static final OfInt month$layout() {
        return month$LAYOUT;
    }

    private static final long month$OFFSET = $LAYOUT.byteOffset(groupElement("month"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int month
     * }
     */
    public static final long month$offset() {
        return month$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int month
     * }
     */
    public static int month(MemorySegment struct) {
        return struct.get(month$LAYOUT, month$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int month
     * }
     */
    public static void month(MemorySegment struct, int fieldValue) {
        struct.set(month$LAYOUT, month$OFFSET, fieldValue);
    }

    private static final OfInt day$LAYOUT = (OfInt)$LAYOUT.select(groupElement("day"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int day
     * }
     */
    public static final OfInt day$layout() {
        return day$LAYOUT;
    }

    private static final long day$OFFSET = $LAYOUT.byteOffset(groupElement("day"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int day
     * }
     */
    public static final long day$offset() {
        return day$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int day
     * }
     */
    public static int day(MemorySegment struct) {
        return struct.get(day$LAYOUT, day$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int day
     * }
     */
    public static void day(MemorySegment struct, int fieldValue) {
        struct.set(day$LAYOUT, day$OFFSET, fieldValue);
    }

    private static final OfInt hour$LAYOUT = (OfInt)$LAYOUT.select(groupElement("hour"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int hour
     * }
     */
    public static final OfInt hour$layout() {
        return hour$LAYOUT;
    }

    private static final long hour$OFFSET = $LAYOUT.byteOffset(groupElement("hour"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int hour
     * }
     */
    public static final long hour$offset() {
        return hour$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int hour
     * }
     */
    public static int hour(MemorySegment struct) {
        return struct.get(hour$LAYOUT, hour$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int hour
     * }
     */
    public static void hour(MemorySegment struct, int fieldValue) {
        struct.set(hour$LAYOUT, hour$OFFSET, fieldValue);
    }

    private static final OfInt minute$LAYOUT = (OfInt)$LAYOUT.select(groupElement("minute"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int minute
     * }
     */
    public static final OfInt minute$layout() {
        return minute$LAYOUT;
    }

    private static final long minute$OFFSET = $LAYOUT.byteOffset(groupElement("minute"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int minute
     * }
     */
    public static final long minute$offset() {
        return minute$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int minute
     * }
     */
    public static int minute(MemorySegment struct) {
        return struct.get(minute$LAYOUT, minute$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int minute
     * }
     */
    public static void minute(MemorySegment struct, int fieldValue) {
        struct.set(minute$LAYOUT, minute$OFFSET, fieldValue);
    }

    private static final OfInt second$LAYOUT = (OfInt)$LAYOUT.select(groupElement("second"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int second
     * }
     */
    public static final OfInt second$layout() {
        return second$LAYOUT;
    }

    private static final long second$OFFSET = $LAYOUT.byteOffset(groupElement("second"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int second
     * }
     */
    public static final long second$offset() {
        return second$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int second
     * }
     */
    public static int second(MemorySegment struct) {
        return struct.get(second$LAYOUT, second$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int second
     * }
     */
    public static void second(MemorySegment struct, int fieldValue) {
        struct.set(second$LAYOUT, second$OFFSET, fieldValue);
    }

    private static final OfInt nanosecond$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nanosecond"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int nanosecond
     * }
     */
    public static final OfInt nanosecond$layout() {
        return nanosecond$LAYOUT;
    }

    private static final long nanosecond$OFFSET = $LAYOUT.byteOffset(groupElement("nanosecond"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int nanosecond
     * }
     */
    public static final long nanosecond$offset() {
        return nanosecond$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int nanosecond
     * }
     */
    public static int nanosecond(MemorySegment struct) {
        return struct.get(nanosecond$LAYOUT, nanosecond$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int nanosecond
     * }
     */
    public static void nanosecond(MemorySegment struct, int fieldValue) {
        struct.set(nanosecond$LAYOUT, nanosecond$OFFSET, fieldValue);
    }

    private static final OfInt day_of_week$LAYOUT = (OfInt)$LAYOUT.select(groupElement("day_of_week"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int day_of_week
     * }
     */
    public static final OfInt day_of_week$layout() {
        return day_of_week$LAYOUT;
    }

    private static final long day_of_week$OFFSET = $LAYOUT.byteOffset(groupElement("day_of_week"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int day_of_week
     * }
     */
    public static final long day_of_week$offset() {
        return day_of_week$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int day_of_week
     * }
     */
    public static int day_of_week(MemorySegment struct) {
        return struct.get(day_of_week$LAYOUT, day_of_week$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int day_of_week
     * }
     */
    public static void day_of_week(MemorySegment struct, int fieldValue) {
        struct.set(day_of_week$LAYOUT, day_of_week$OFFSET, fieldValue);
    }

    private static final OfInt utc_offset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("utc_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int utc_offset
     * }
     */
    public static final OfInt utc_offset$layout() {
        return utc_offset$LAYOUT;
    }

    private static final long utc_offset$OFFSET = $LAYOUT.byteOffset(groupElement("utc_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int utc_offset
     * }
     */
    public static final long utc_offset$offset() {
        return utc_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int utc_offset
     * }
     */
    public static int utc_offset(MemorySegment struct) {
        return struct.get(utc_offset$LAYOUT, utc_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int utc_offset
     * }
     */
    public static void utc_offset(MemorySegment struct, int fieldValue) {
        struct.set(utc_offset$LAYOUT, utc_offset$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

