// Generated by jextract

package de.hpi.swa.trufflesqueak.shared.sdl.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_GPUStencilOpState {
 *     SDL_GPUStencilOp fail_op;
 *     SDL_GPUStencilOp pass_op;
 *     SDL_GPUStencilOp depth_fail_op;
 *     SDL_GPUCompareOp compare_op;
 * }
 * }
 */
public class SDL_GPUStencilOpState {

    SDL_GPUStencilOpState() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_INT.withName("fail_op"),
        SDL_h.C_INT.withName("pass_op"),
        SDL_h.C_INT.withName("depth_fail_op"),
        SDL_h.C_INT.withName("compare_op")
    ).withName("SDL_GPUStencilOpState");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt fail_op$LAYOUT = (OfInt)$LAYOUT.select(groupElement("fail_op"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOp fail_op
     * }
     */
    public static final OfInt fail_op$layout() {
        return fail_op$LAYOUT;
    }

    private static final long fail_op$OFFSET = $LAYOUT.byteOffset(groupElement("fail_op"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOp fail_op
     * }
     */
    public static final long fail_op$offset() {
        return fail_op$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOp fail_op
     * }
     */
    public static int fail_op(MemorySegment struct) {
        return struct.get(fail_op$LAYOUT, fail_op$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOp fail_op
     * }
     */
    public static void fail_op(MemorySegment struct, int fieldValue) {
        struct.set(fail_op$LAYOUT, fail_op$OFFSET, fieldValue);
    }

    private static final OfInt pass_op$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pass_op"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOp pass_op
     * }
     */
    public static final OfInt pass_op$layout() {
        return pass_op$LAYOUT;
    }

    private static final long pass_op$OFFSET = $LAYOUT.byteOffset(groupElement("pass_op"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOp pass_op
     * }
     */
    public static final long pass_op$offset() {
        return pass_op$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOp pass_op
     * }
     */
    public static int pass_op(MemorySegment struct) {
        return struct.get(pass_op$LAYOUT, pass_op$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOp pass_op
     * }
     */
    public static void pass_op(MemorySegment struct, int fieldValue) {
        struct.set(pass_op$LAYOUT, pass_op$OFFSET, fieldValue);
    }

    private static final OfInt depth_fail_op$LAYOUT = (OfInt)$LAYOUT.select(groupElement("depth_fail_op"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOp depth_fail_op
     * }
     */
    public static final OfInt depth_fail_op$layout() {
        return depth_fail_op$LAYOUT;
    }

    private static final long depth_fail_op$OFFSET = $LAYOUT.byteOffset(groupElement("depth_fail_op"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOp depth_fail_op
     * }
     */
    public static final long depth_fail_op$offset() {
        return depth_fail_op$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOp depth_fail_op
     * }
     */
    public static int depth_fail_op(MemorySegment struct) {
        return struct.get(depth_fail_op$LAYOUT, depth_fail_op$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOp depth_fail_op
     * }
     */
    public static void depth_fail_op(MemorySegment struct, int fieldValue) {
        struct.set(depth_fail_op$LAYOUT, depth_fail_op$OFFSET, fieldValue);
    }

    private static final OfInt compare_op$LAYOUT = (OfInt)$LAYOUT.select(groupElement("compare_op"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUCompareOp compare_op
     * }
     */
    public static final OfInt compare_op$layout() {
        return compare_op$LAYOUT;
    }

    private static final long compare_op$OFFSET = $LAYOUT.byteOffset(groupElement("compare_op"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUCompareOp compare_op
     * }
     */
    public static final long compare_op$offset() {
        return compare_op$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUCompareOp compare_op
     * }
     */
    public static int compare_op(MemorySegment struct) {
        return struct.get(compare_op$LAYOUT, compare_op$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUCompareOp compare_op
     * }
     */
    public static void compare_op(MemorySegment struct, int fieldValue) {
        struct.set(compare_op$LAYOUT, compare_op$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

