// Generated by jextract

package de.hpi.swa.trufflesqueak.shared.sdl.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_GPUStorageBufferReadWriteBinding {
 *     SDL_GPUBuffer *buffer;
 *     bool cycle;
 *     Uint8 padding1;
 *     Uint8 padding2;
 *     Uint8 padding3;
 * }
 * }
 */
public class SDL_GPUStorageBufferReadWriteBinding {

    SDL_GPUStorageBufferReadWriteBinding() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_POINTER.withName("buffer"),
        SDL_h.C_BOOL.withName("cycle"),
        SDL_h.C_CHAR.withName("padding1"),
        SDL_h.C_CHAR.withName("padding2"),
        SDL_h.C_CHAR.withName("padding3"),
        MemoryLayout.paddingLayout(4)
    ).withName("SDL_GPUStorageBufferReadWriteBinding");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout buffer$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("buffer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUBuffer *buffer
     * }
     */
    public static final AddressLayout buffer$layout() {
        return buffer$LAYOUT;
    }

    private static final long buffer$OFFSET = $LAYOUT.byteOffset(groupElement("buffer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUBuffer *buffer
     * }
     */
    public static final long buffer$offset() {
        return buffer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUBuffer *buffer
     * }
     */
    public static MemorySegment buffer(MemorySegment struct) {
        return struct.get(buffer$LAYOUT, buffer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUBuffer *buffer
     * }
     */
    public static void buffer(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(buffer$LAYOUT, buffer$OFFSET, fieldValue);
    }

    private static final OfBoolean cycle$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("cycle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool cycle
     * }
     */
    public static final OfBoolean cycle$layout() {
        return cycle$LAYOUT;
    }

    private static final long cycle$OFFSET = $LAYOUT.byteOffset(groupElement("cycle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool cycle
     * }
     */
    public static final long cycle$offset() {
        return cycle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool cycle
     * }
     */
    public static boolean cycle(MemorySegment struct) {
        return struct.get(cycle$LAYOUT, cycle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool cycle
     * }
     */
    public static void cycle(MemorySegment struct, boolean fieldValue) {
        struct.set(cycle$LAYOUT, cycle$OFFSET, fieldValue);
    }

    private static final OfByte padding1$LAYOUT = (OfByte)$LAYOUT.select(groupElement("padding1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static final OfByte padding1$layout() {
        return padding1$LAYOUT;
    }

    private static final long padding1$OFFSET = $LAYOUT.byteOffset(groupElement("padding1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static final long padding1$offset() {
        return padding1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static byte padding1(MemorySegment struct) {
        return struct.get(padding1$LAYOUT, padding1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static void padding1(MemorySegment struct, byte fieldValue) {
        struct.set(padding1$LAYOUT, padding1$OFFSET, fieldValue);
    }

    private static final OfByte padding2$LAYOUT = (OfByte)$LAYOUT.select(groupElement("padding2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static final OfByte padding2$layout() {
        return padding2$LAYOUT;
    }

    private static final long padding2$OFFSET = $LAYOUT.byteOffset(groupElement("padding2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static final long padding2$offset() {
        return padding2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static byte padding2(MemorySegment struct) {
        return struct.get(padding2$LAYOUT, padding2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static void padding2(MemorySegment struct, byte fieldValue) {
        struct.set(padding2$LAYOUT, padding2$OFFSET, fieldValue);
    }

    private static final OfByte padding3$LAYOUT = (OfByte)$LAYOUT.select(groupElement("padding3"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static final OfByte padding3$layout() {
        return padding3$LAYOUT;
    }

    private static final long padding3$OFFSET = $LAYOUT.byteOffset(groupElement("padding3"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static final long padding3$offset() {
        return padding3$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static byte padding3(MemorySegment struct) {
        return struct.get(padding3$LAYOUT, padding3$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static void padding3(MemorySegment struct, byte fieldValue) {
        struct.set(padding3$LAYOUT, padding3$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

