// Generated by jextract

package de.hpi.swa.trufflesqueak.shared.sdl.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_GPUMultisampleState {
 *     SDL_GPUSampleCount sample_count;
 *     Uint32 sample_mask;
 *     bool enable_mask;
 *     bool enable_alpha_to_coverage;
 *     Uint8 padding2;
 *     Uint8 padding3;
 * }
 * }
 */
public class SDL_GPUMultisampleState {

    SDL_GPUMultisampleState() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_INT.withName("sample_count"),
        SDL_h.C_INT.withName("sample_mask"),
        SDL_h.C_BOOL.withName("enable_mask"),
        SDL_h.C_BOOL.withName("enable_alpha_to_coverage"),
        SDL_h.C_CHAR.withName("padding2"),
        SDL_h.C_CHAR.withName("padding3")
    ).withName("SDL_GPUMultisampleState");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt sample_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sample_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUSampleCount sample_count
     * }
     */
    public static final OfInt sample_count$layout() {
        return sample_count$LAYOUT;
    }

    private static final long sample_count$OFFSET = $LAYOUT.byteOffset(groupElement("sample_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUSampleCount sample_count
     * }
     */
    public static final long sample_count$offset() {
        return sample_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUSampleCount sample_count
     * }
     */
    public static int sample_count(MemorySegment struct) {
        return struct.get(sample_count$LAYOUT, sample_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUSampleCount sample_count
     * }
     */
    public static void sample_count(MemorySegment struct, int fieldValue) {
        struct.set(sample_count$LAYOUT, sample_count$OFFSET, fieldValue);
    }

    private static final OfInt sample_mask$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sample_mask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 sample_mask
     * }
     */
    public static final OfInt sample_mask$layout() {
        return sample_mask$LAYOUT;
    }

    private static final long sample_mask$OFFSET = $LAYOUT.byteOffset(groupElement("sample_mask"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 sample_mask
     * }
     */
    public static final long sample_mask$offset() {
        return sample_mask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 sample_mask
     * }
     */
    public static int sample_mask(MemorySegment struct) {
        return struct.get(sample_mask$LAYOUT, sample_mask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 sample_mask
     * }
     */
    public static void sample_mask(MemorySegment struct, int fieldValue) {
        struct.set(sample_mask$LAYOUT, sample_mask$OFFSET, fieldValue);
    }

    private static final OfBoolean enable_mask$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enable_mask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool enable_mask
     * }
     */
    public static final OfBoolean enable_mask$layout() {
        return enable_mask$LAYOUT;
    }

    private static final long enable_mask$OFFSET = $LAYOUT.byteOffset(groupElement("enable_mask"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool enable_mask
     * }
     */
    public static final long enable_mask$offset() {
        return enable_mask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool enable_mask
     * }
     */
    public static boolean enable_mask(MemorySegment struct) {
        return struct.get(enable_mask$LAYOUT, enable_mask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool enable_mask
     * }
     */
    public static void enable_mask(MemorySegment struct, boolean fieldValue) {
        struct.set(enable_mask$LAYOUT, enable_mask$OFFSET, fieldValue);
    }

    private static final OfBoolean enable_alpha_to_coverage$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enable_alpha_to_coverage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool enable_alpha_to_coverage
     * }
     */
    public static final OfBoolean enable_alpha_to_coverage$layout() {
        return enable_alpha_to_coverage$LAYOUT;
    }

    private static final long enable_alpha_to_coverage$OFFSET = $LAYOUT.byteOffset(groupElement("enable_alpha_to_coverage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool enable_alpha_to_coverage
     * }
     */
    public static final long enable_alpha_to_coverage$offset() {
        return enable_alpha_to_coverage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool enable_alpha_to_coverage
     * }
     */
    public static boolean enable_alpha_to_coverage(MemorySegment struct) {
        return struct.get(enable_alpha_to_coverage$LAYOUT, enable_alpha_to_coverage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool enable_alpha_to_coverage
     * }
     */
    public static void enable_alpha_to_coverage(MemorySegment struct, boolean fieldValue) {
        struct.set(enable_alpha_to_coverage$LAYOUT, enable_alpha_to_coverage$OFFSET, fieldValue);
    }

    private static final OfByte padding2$LAYOUT = (OfByte)$LAYOUT.select(groupElement("padding2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static final OfByte padding2$layout() {
        return padding2$LAYOUT;
    }

    private static final long padding2$OFFSET = $LAYOUT.byteOffset(groupElement("padding2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static final long padding2$offset() {
        return padding2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static byte padding2(MemorySegment struct) {
        return struct.get(padding2$LAYOUT, padding2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static void padding2(MemorySegment struct, byte fieldValue) {
        struct.set(padding2$LAYOUT, padding2$OFFSET, fieldValue);
    }

    private static final OfByte padding3$LAYOUT = (OfByte)$LAYOUT.select(groupElement("padding3"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static final OfByte padding3$layout() {
        return padding3$LAYOUT;
    }

    private static final long padding3$OFFSET = $LAYOUT.byteOffset(groupElement("padding3"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static final long padding3$offset() {
        return padding3$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static byte padding3(MemorySegment struct) {
        return struct.get(padding3$LAYOUT, padding3$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static void padding3(MemorySegment struct, byte fieldValue) {
        struct.set(padding3$LAYOUT, padding3$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

