// Generated by jextract

package de.hpi.swa.trufflesqueak.shared.sdl.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_GPUColorTargetInfo {
 *     SDL_GPUTexture *texture;
 *     Uint32 mip_level;
 *     Uint32 layer_or_depth_plane;
 *     SDL_FColor clear_color;
 *     SDL_GPULoadOp load_op;
 *     SDL_GPUStoreOp store_op;
 *     SDL_GPUTexture *resolve_texture;
 *     Uint32 resolve_mip_level;
 *     Uint32 resolve_layer;
 *     bool cycle;
 *     bool cycle_resolve_texture;
 *     Uint8 padding1;
 *     Uint8 padding2;
 * }
 * }
 */
public class SDL_GPUColorTargetInfo {

    SDL_GPUColorTargetInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_POINTER.withName("texture"),
        SDL_h.C_INT.withName("mip_level"),
        SDL_h.C_INT.withName("layer_or_depth_plane"),
        SDL_FColor.layout().withName("clear_color"),
        SDL_h.C_INT.withName("load_op"),
        SDL_h.C_INT.withName("store_op"),
        SDL_h.C_POINTER.withName("resolve_texture"),
        SDL_h.C_INT.withName("resolve_mip_level"),
        SDL_h.C_INT.withName("resolve_layer"),
        SDL_h.C_BOOL.withName("cycle"),
        SDL_h.C_BOOL.withName("cycle_resolve_texture"),
        SDL_h.C_CHAR.withName("padding1"),
        SDL_h.C_CHAR.withName("padding2"),
        MemoryLayout.paddingLayout(4)
    ).withName("SDL_GPUColorTargetInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout texture$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("texture"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUTexture *texture
     * }
     */
    public static final AddressLayout texture$layout() {
        return texture$LAYOUT;
    }

    private static final long texture$OFFSET = $LAYOUT.byteOffset(groupElement("texture"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUTexture *texture
     * }
     */
    public static final long texture$offset() {
        return texture$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUTexture *texture
     * }
     */
    public static MemorySegment texture(MemorySegment struct) {
        return struct.get(texture$LAYOUT, texture$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUTexture *texture
     * }
     */
    public static void texture(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(texture$LAYOUT, texture$OFFSET, fieldValue);
    }

    private static final OfInt mip_level$LAYOUT = (OfInt)$LAYOUT.select(groupElement("mip_level"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 mip_level
     * }
     */
    public static final OfInt mip_level$layout() {
        return mip_level$LAYOUT;
    }

    private static final long mip_level$OFFSET = $LAYOUT.byteOffset(groupElement("mip_level"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 mip_level
     * }
     */
    public static final long mip_level$offset() {
        return mip_level$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 mip_level
     * }
     */
    public static int mip_level(MemorySegment struct) {
        return struct.get(mip_level$LAYOUT, mip_level$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 mip_level
     * }
     */
    public static void mip_level(MemorySegment struct, int fieldValue) {
        struct.set(mip_level$LAYOUT, mip_level$OFFSET, fieldValue);
    }

    private static final OfInt layer_or_depth_plane$LAYOUT = (OfInt)$LAYOUT.select(groupElement("layer_or_depth_plane"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 layer_or_depth_plane
     * }
     */
    public static final OfInt layer_or_depth_plane$layout() {
        return layer_or_depth_plane$LAYOUT;
    }

    private static final long layer_or_depth_plane$OFFSET = $LAYOUT.byteOffset(groupElement("layer_or_depth_plane"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 layer_or_depth_plane
     * }
     */
    public static final long layer_or_depth_plane$offset() {
        return layer_or_depth_plane$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 layer_or_depth_plane
     * }
     */
    public static int layer_or_depth_plane(MemorySegment struct) {
        return struct.get(layer_or_depth_plane$LAYOUT, layer_or_depth_plane$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 layer_or_depth_plane
     * }
     */
    public static void layer_or_depth_plane(MemorySegment struct, int fieldValue) {
        struct.set(layer_or_depth_plane$LAYOUT, layer_or_depth_plane$OFFSET, fieldValue);
    }

    private static final GroupLayout clear_color$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("clear_color"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_FColor clear_color
     * }
     */
    public static final GroupLayout clear_color$layout() {
        return clear_color$LAYOUT;
    }

    private static final long clear_color$OFFSET = $LAYOUT.byteOffset(groupElement("clear_color"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_FColor clear_color
     * }
     */
    public static final long clear_color$offset() {
        return clear_color$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_FColor clear_color
     * }
     */
    public static MemorySegment clear_color(MemorySegment struct) {
        return struct.asSlice(clear_color$OFFSET, clear_color$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_FColor clear_color
     * }
     */
    public static void clear_color(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, clear_color$OFFSET, clear_color$LAYOUT.byteSize());
    }

    private static final OfInt load_op$LAYOUT = (OfInt)$LAYOUT.select(groupElement("load_op"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPULoadOp load_op
     * }
     */
    public static final OfInt load_op$layout() {
        return load_op$LAYOUT;
    }

    private static final long load_op$OFFSET = $LAYOUT.byteOffset(groupElement("load_op"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPULoadOp load_op
     * }
     */
    public static final long load_op$offset() {
        return load_op$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPULoadOp load_op
     * }
     */
    public static int load_op(MemorySegment struct) {
        return struct.get(load_op$LAYOUT, load_op$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPULoadOp load_op
     * }
     */
    public static void load_op(MemorySegment struct, int fieldValue) {
        struct.set(load_op$LAYOUT, load_op$OFFSET, fieldValue);
    }

    private static final OfInt store_op$LAYOUT = (OfInt)$LAYOUT.select(groupElement("store_op"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUStoreOp store_op
     * }
     */
    public static final OfInt store_op$layout() {
        return store_op$LAYOUT;
    }

    private static final long store_op$OFFSET = $LAYOUT.byteOffset(groupElement("store_op"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUStoreOp store_op
     * }
     */
    public static final long store_op$offset() {
        return store_op$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUStoreOp store_op
     * }
     */
    public static int store_op(MemorySegment struct) {
        return struct.get(store_op$LAYOUT, store_op$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUStoreOp store_op
     * }
     */
    public static void store_op(MemorySegment struct, int fieldValue) {
        struct.set(store_op$LAYOUT, store_op$OFFSET, fieldValue);
    }

    private static final AddressLayout resolve_texture$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("resolve_texture"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUTexture *resolve_texture
     * }
     */
    public static final AddressLayout resolve_texture$layout() {
        return resolve_texture$LAYOUT;
    }

    private static final long resolve_texture$OFFSET = $LAYOUT.byteOffset(groupElement("resolve_texture"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUTexture *resolve_texture
     * }
     */
    public static final long resolve_texture$offset() {
        return resolve_texture$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUTexture *resolve_texture
     * }
     */
    public static MemorySegment resolve_texture(MemorySegment struct) {
        return struct.get(resolve_texture$LAYOUT, resolve_texture$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUTexture *resolve_texture
     * }
     */
    public static void resolve_texture(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(resolve_texture$LAYOUT, resolve_texture$OFFSET, fieldValue);
    }

    private static final OfInt resolve_mip_level$LAYOUT = (OfInt)$LAYOUT.select(groupElement("resolve_mip_level"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 resolve_mip_level
     * }
     */
    public static final OfInt resolve_mip_level$layout() {
        return resolve_mip_level$LAYOUT;
    }

    private static final long resolve_mip_level$OFFSET = $LAYOUT.byteOffset(groupElement("resolve_mip_level"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 resolve_mip_level
     * }
     */
    public static final long resolve_mip_level$offset() {
        return resolve_mip_level$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 resolve_mip_level
     * }
     */
    public static int resolve_mip_level(MemorySegment struct) {
        return struct.get(resolve_mip_level$LAYOUT, resolve_mip_level$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 resolve_mip_level
     * }
     */
    public static void resolve_mip_level(MemorySegment struct, int fieldValue) {
        struct.set(resolve_mip_level$LAYOUT, resolve_mip_level$OFFSET, fieldValue);
    }

    private static final OfInt resolve_layer$LAYOUT = (OfInt)$LAYOUT.select(groupElement("resolve_layer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 resolve_layer
     * }
     */
    public static final OfInt resolve_layer$layout() {
        return resolve_layer$LAYOUT;
    }

    private static final long resolve_layer$OFFSET = $LAYOUT.byteOffset(groupElement("resolve_layer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 resolve_layer
     * }
     */
    public static final long resolve_layer$offset() {
        return resolve_layer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 resolve_layer
     * }
     */
    public static int resolve_layer(MemorySegment struct) {
        return struct.get(resolve_layer$LAYOUT, resolve_layer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 resolve_layer
     * }
     */
    public static void resolve_layer(MemorySegment struct, int fieldValue) {
        struct.set(resolve_layer$LAYOUT, resolve_layer$OFFSET, fieldValue);
    }

    private static final OfBoolean cycle$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("cycle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool cycle
     * }
     */
    public static final OfBoolean cycle$layout() {
        return cycle$LAYOUT;
    }

    private static final long cycle$OFFSET = $LAYOUT.byteOffset(groupElement("cycle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool cycle
     * }
     */
    public static final long cycle$offset() {
        return cycle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool cycle
     * }
     */
    public static boolean cycle(MemorySegment struct) {
        return struct.get(cycle$LAYOUT, cycle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool cycle
     * }
     */
    public static void cycle(MemorySegment struct, boolean fieldValue) {
        struct.set(cycle$LAYOUT, cycle$OFFSET, fieldValue);
    }

    private static final OfBoolean cycle_resolve_texture$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("cycle_resolve_texture"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool cycle_resolve_texture
     * }
     */
    public static final OfBoolean cycle_resolve_texture$layout() {
        return cycle_resolve_texture$LAYOUT;
    }

    private static final long cycle_resolve_texture$OFFSET = $LAYOUT.byteOffset(groupElement("cycle_resolve_texture"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool cycle_resolve_texture
     * }
     */
    public static final long cycle_resolve_texture$offset() {
        return cycle_resolve_texture$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool cycle_resolve_texture
     * }
     */
    public static boolean cycle_resolve_texture(MemorySegment struct) {
        return struct.get(cycle_resolve_texture$LAYOUT, cycle_resolve_texture$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool cycle_resolve_texture
     * }
     */
    public static void cycle_resolve_texture(MemorySegment struct, boolean fieldValue) {
        struct.set(cycle_resolve_texture$LAYOUT, cycle_resolve_texture$OFFSET, fieldValue);
    }

    private static final OfByte padding1$LAYOUT = (OfByte)$LAYOUT.select(groupElement("padding1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static final OfByte padding1$layout() {
        return padding1$LAYOUT;
    }

    private static final long padding1$OFFSET = $LAYOUT.byteOffset(groupElement("padding1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static final long padding1$offset() {
        return padding1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static byte padding1(MemorySegment struct) {
        return struct.get(padding1$LAYOUT, padding1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static void padding1(MemorySegment struct, byte fieldValue) {
        struct.set(padding1$LAYOUT, padding1$OFFSET, fieldValue);
    }

    private static final OfByte padding2$LAYOUT = (OfByte)$LAYOUT.select(groupElement("padding2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static final OfByte padding2$layout() {
        return padding2$LAYOUT;
    }

    private static final long padding2$OFFSET = $LAYOUT.byteOffset(groupElement("padding2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static final long padding2$offset() {
        return padding2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static byte padding2(MemorySegment struct) {
        return struct.get(padding2$LAYOUT, padding2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static void padding2(MemorySegment struct, byte fieldValue) {
        struct.set(padding2$LAYOUT, padding2$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

