// Generated by jextract

package de.hpi.swa.trufflesqueak.shared.sdl.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_GPUShaderCreateInfo {
 *     size_t code_size;
 *     const Uint8 *code;
 *     const char *entrypoint;
 *     SDL_GPUShaderFormat format;
 *     SDL_GPUShaderStage stage;
 *     Uint32 num_samplers;
 *     Uint32 num_storage_textures;
 *     Uint32 num_storage_buffers;
 *     Uint32 num_uniform_buffers;
 *     SDL_PropertiesID props;
 * }
 * }
 */
public class SDL_GPUShaderCreateInfo {

    SDL_GPUShaderCreateInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_LONG.withName("code_size"),
        SDL_h.C_POINTER.withName("code"),
        SDL_h.C_POINTER.withName("entrypoint"),
        SDL_h.C_INT.withName("format"),
        SDL_h.C_INT.withName("stage"),
        SDL_h.C_INT.withName("num_samplers"),
        SDL_h.C_INT.withName("num_storage_textures"),
        SDL_h.C_INT.withName("num_storage_buffers"),
        SDL_h.C_INT.withName("num_uniform_buffers"),
        SDL_h.C_INT.withName("props"),
        MemoryLayout.paddingLayout(4)
    ).withName("SDL_GPUShaderCreateInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong code_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("code_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t code_size
     * }
     */
    public static final OfLong code_size$layout() {
        return code_size$LAYOUT;
    }

    private static final long code_size$OFFSET = $LAYOUT.byteOffset(groupElement("code_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t code_size
     * }
     */
    public static final long code_size$offset() {
        return code_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t code_size
     * }
     */
    public static long code_size(MemorySegment struct) {
        return struct.get(code_size$LAYOUT, code_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t code_size
     * }
     */
    public static void code_size(MemorySegment struct, long fieldValue) {
        struct.set(code_size$LAYOUT, code_size$OFFSET, fieldValue);
    }

    private static final AddressLayout code$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("code"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const Uint8 *code
     * }
     */
    public static final AddressLayout code$layout() {
        return code$LAYOUT;
    }

    private static final long code$OFFSET = $LAYOUT.byteOffset(groupElement("code"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const Uint8 *code
     * }
     */
    public static final long code$offset() {
        return code$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const Uint8 *code
     * }
     */
    public static MemorySegment code(MemorySegment struct) {
        return struct.get(code$LAYOUT, code$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const Uint8 *code
     * }
     */
    public static void code(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(code$LAYOUT, code$OFFSET, fieldValue);
    }

    private static final AddressLayout entrypoint$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("entrypoint"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *entrypoint
     * }
     */
    public static final AddressLayout entrypoint$layout() {
        return entrypoint$LAYOUT;
    }

    private static final long entrypoint$OFFSET = $LAYOUT.byteOffset(groupElement("entrypoint"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *entrypoint
     * }
     */
    public static final long entrypoint$offset() {
        return entrypoint$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *entrypoint
     * }
     */
    public static MemorySegment entrypoint(MemorySegment struct) {
        return struct.get(entrypoint$LAYOUT, entrypoint$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *entrypoint
     * }
     */
    public static void entrypoint(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(entrypoint$LAYOUT, entrypoint$OFFSET, fieldValue);
    }

    private static final OfInt format$LAYOUT = (OfInt)$LAYOUT.select(groupElement("format"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUShaderFormat format
     * }
     */
    public static final OfInt format$layout() {
        return format$LAYOUT;
    }

    private static final long format$OFFSET = $LAYOUT.byteOffset(groupElement("format"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUShaderFormat format
     * }
     */
    public static final long format$offset() {
        return format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUShaderFormat format
     * }
     */
    public static int format(MemorySegment struct) {
        return struct.get(format$LAYOUT, format$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUShaderFormat format
     * }
     */
    public static void format(MemorySegment struct, int fieldValue) {
        struct.set(format$LAYOUT, format$OFFSET, fieldValue);
    }

    private static final OfInt stage$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUShaderStage stage
     * }
     */
    public static final OfInt stage$layout() {
        return stage$LAYOUT;
    }

    private static final long stage$OFFSET = $LAYOUT.byteOffset(groupElement("stage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUShaderStage stage
     * }
     */
    public static final long stage$offset() {
        return stage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUShaderStage stage
     * }
     */
    public static int stage(MemorySegment struct) {
        return struct.get(stage$LAYOUT, stage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUShaderStage stage
     * }
     */
    public static void stage(MemorySegment struct, int fieldValue) {
        struct.set(stage$LAYOUT, stage$OFFSET, fieldValue);
    }

    private static final OfInt num_samplers$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_samplers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 num_samplers
     * }
     */
    public static final OfInt num_samplers$layout() {
        return num_samplers$LAYOUT;
    }

    private static final long num_samplers$OFFSET = $LAYOUT.byteOffset(groupElement("num_samplers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 num_samplers
     * }
     */
    public static final long num_samplers$offset() {
        return num_samplers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 num_samplers
     * }
     */
    public static int num_samplers(MemorySegment struct) {
        return struct.get(num_samplers$LAYOUT, num_samplers$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 num_samplers
     * }
     */
    public static void num_samplers(MemorySegment struct, int fieldValue) {
        struct.set(num_samplers$LAYOUT, num_samplers$OFFSET, fieldValue);
    }

    private static final OfInt num_storage_textures$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_storage_textures"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 num_storage_textures
     * }
     */
    public static final OfInt num_storage_textures$layout() {
        return num_storage_textures$LAYOUT;
    }

    private static final long num_storage_textures$OFFSET = $LAYOUT.byteOffset(groupElement("num_storage_textures"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 num_storage_textures
     * }
     */
    public static final long num_storage_textures$offset() {
        return num_storage_textures$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 num_storage_textures
     * }
     */
    public static int num_storage_textures(MemorySegment struct) {
        return struct.get(num_storage_textures$LAYOUT, num_storage_textures$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 num_storage_textures
     * }
     */
    public static void num_storage_textures(MemorySegment struct, int fieldValue) {
        struct.set(num_storage_textures$LAYOUT, num_storage_textures$OFFSET, fieldValue);
    }

    private static final OfInt num_storage_buffers$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_storage_buffers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 num_storage_buffers
     * }
     */
    public static final OfInt num_storage_buffers$layout() {
        return num_storage_buffers$LAYOUT;
    }

    private static final long num_storage_buffers$OFFSET = $LAYOUT.byteOffset(groupElement("num_storage_buffers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 num_storage_buffers
     * }
     */
    public static final long num_storage_buffers$offset() {
        return num_storage_buffers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 num_storage_buffers
     * }
     */
    public static int num_storage_buffers(MemorySegment struct) {
        return struct.get(num_storage_buffers$LAYOUT, num_storage_buffers$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 num_storage_buffers
     * }
     */
    public static void num_storage_buffers(MemorySegment struct, int fieldValue) {
        struct.set(num_storage_buffers$LAYOUT, num_storage_buffers$OFFSET, fieldValue);
    }

    private static final OfInt num_uniform_buffers$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_uniform_buffers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 num_uniform_buffers
     * }
     */
    public static final OfInt num_uniform_buffers$layout() {
        return num_uniform_buffers$LAYOUT;
    }

    private static final long num_uniform_buffers$OFFSET = $LAYOUT.byteOffset(groupElement("num_uniform_buffers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 num_uniform_buffers
     * }
     */
    public static final long num_uniform_buffers$offset() {
        return num_uniform_buffers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 num_uniform_buffers
     * }
     */
    public static int num_uniform_buffers(MemorySegment struct) {
        return struct.get(num_uniform_buffers$LAYOUT, num_uniform_buffers$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 num_uniform_buffers
     * }
     */
    public static void num_uniform_buffers(MemorySegment struct, int fieldValue) {
        struct.set(num_uniform_buffers$LAYOUT, num_uniform_buffers$OFFSET, fieldValue);
    }

    private static final OfInt props$LAYOUT = (OfInt)$LAYOUT.select(groupElement("props"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_PropertiesID props
     * }
     */
    public static final OfInt props$layout() {
        return props$LAYOUT;
    }

    private static final long props$OFFSET = $LAYOUT.byteOffset(groupElement("props"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_PropertiesID props
     * }
     */
    public static final long props$offset() {
        return props$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_PropertiesID props
     * }
     */
    public static int props(MemorySegment struct) {
        return struct.get(props$LAYOUT, props$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_PropertiesID props
     * }
     */
    public static void props(MemorySegment struct, int fieldValue) {
        struct.set(props$LAYOUT, props$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

