// Generated by jextract

package de.hpi.swa.trufflesqueak.shared.sdl.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_VirtualJoystickTouchpadDesc {
 *     Uint16 nfingers;
 *     Uint16 padding[3];
 * }
 * }
 */
public class SDL_VirtualJoystickTouchpadDesc {

    SDL_VirtualJoystickTouchpadDesc() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_SHORT.withName("nfingers"),
        MemoryLayout.sequenceLayout(3, SDL_h.C_SHORT).withName("padding")
    ).withName("SDL_VirtualJoystickTouchpadDesc");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfShort nfingers$LAYOUT = (OfShort)$LAYOUT.select(groupElement("nfingers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 nfingers
     * }
     */
    public static final OfShort nfingers$layout() {
        return nfingers$LAYOUT;
    }

    private static final long nfingers$OFFSET = $LAYOUT.byteOffset(groupElement("nfingers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 nfingers
     * }
     */
    public static final long nfingers$offset() {
        return nfingers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 nfingers
     * }
     */
    public static short nfingers(MemorySegment struct) {
        return struct.get(nfingers$LAYOUT, nfingers$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 nfingers
     * }
     */
    public static void nfingers(MemorySegment struct, short fieldValue) {
        struct.set(nfingers$LAYOUT, nfingers$OFFSET, fieldValue);
    }

    private static final SequenceLayout padding$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("padding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 padding[3]
     * }
     */
    public static final SequenceLayout padding$layout() {
        return padding$LAYOUT;
    }

    private static final long padding$OFFSET = $LAYOUT.byteOffset(groupElement("padding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 padding[3]
     * }
     */
    public static final long padding$offset() {
        return padding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 padding[3]
     * }
     */
    public static MemorySegment padding(MemorySegment struct) {
        return struct.asSlice(padding$OFFSET, padding$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 padding[3]
     * }
     */
    public static void padding(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, padding$OFFSET, padding$LAYOUT.byteSize());
    }

    private static long[] padding$DIMS = { 3 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * Uint16 padding[3]
     * }
     */
    public static long[] padding$dimensions() {
        return padding$DIMS;
    }
    private static final VarHandle padding$ELEM_HANDLE = padding$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * Uint16 padding[3]
     * }
     */
    public static short padding(MemorySegment struct, long index0) {
        return (short)padding$ELEM_HANDLE.get(struct, padding$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * Uint16 padding[3]
     * }
     */
    public static void padding(MemorySegment struct, long index0, short fieldValue) {
        padding$ELEM_HANDLE.set(struct, padding$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

