// Generated by jextract

package de.hpi.swa.trufflesqueak.shared.sdl.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_GPUVulkanOptions {
 *     Uint32 vulkan_api_version;
 *     void *feature_list;
 *     void *vulkan_10_physical_device_features;
 *     Uint32 device_extension_count;
 *     const char **device_extension_names;
 *     Uint32 instance_extension_count;
 *     const char **instance_extension_names;
 * }
 * }
 */
public class SDL_GPUVulkanOptions {

    SDL_GPUVulkanOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_INT.withName("vulkan_api_version"),
        MemoryLayout.paddingLayout(4),
        SDL_h.C_POINTER.withName("feature_list"),
        SDL_h.C_POINTER.withName("vulkan_10_physical_device_features"),
        SDL_h.C_INT.withName("device_extension_count"),
        MemoryLayout.paddingLayout(4),
        SDL_h.C_POINTER.withName("device_extension_names"),
        SDL_h.C_INT.withName("instance_extension_count"),
        MemoryLayout.paddingLayout(4),
        SDL_h.C_POINTER.withName("instance_extension_names")
    ).withName("SDL_GPUVulkanOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt vulkan_api_version$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vulkan_api_version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 vulkan_api_version
     * }
     */
    public static final OfInt vulkan_api_version$layout() {
        return vulkan_api_version$LAYOUT;
    }

    private static final long vulkan_api_version$OFFSET = $LAYOUT.byteOffset(groupElement("vulkan_api_version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 vulkan_api_version
     * }
     */
    public static final long vulkan_api_version$offset() {
        return vulkan_api_version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 vulkan_api_version
     * }
     */
    public static int vulkan_api_version(MemorySegment struct) {
        return struct.get(vulkan_api_version$LAYOUT, vulkan_api_version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 vulkan_api_version
     * }
     */
    public static void vulkan_api_version(MemorySegment struct, int fieldValue) {
        struct.set(vulkan_api_version$LAYOUT, vulkan_api_version$OFFSET, fieldValue);
    }

    private static final AddressLayout feature_list$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("feature_list"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *feature_list
     * }
     */
    public static final AddressLayout feature_list$layout() {
        return feature_list$LAYOUT;
    }

    private static final long feature_list$OFFSET = $LAYOUT.byteOffset(groupElement("feature_list"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *feature_list
     * }
     */
    public static final long feature_list$offset() {
        return feature_list$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *feature_list
     * }
     */
    public static MemorySegment feature_list(MemorySegment struct) {
        return struct.get(feature_list$LAYOUT, feature_list$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *feature_list
     * }
     */
    public static void feature_list(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(feature_list$LAYOUT, feature_list$OFFSET, fieldValue);
    }

    private static final AddressLayout vulkan_10_physical_device_features$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("vulkan_10_physical_device_features"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *vulkan_10_physical_device_features
     * }
     */
    public static final AddressLayout vulkan_10_physical_device_features$layout() {
        return vulkan_10_physical_device_features$LAYOUT;
    }

    private static final long vulkan_10_physical_device_features$OFFSET = $LAYOUT.byteOffset(groupElement("vulkan_10_physical_device_features"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *vulkan_10_physical_device_features
     * }
     */
    public static final long vulkan_10_physical_device_features$offset() {
        return vulkan_10_physical_device_features$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *vulkan_10_physical_device_features
     * }
     */
    public static MemorySegment vulkan_10_physical_device_features(MemorySegment struct) {
        return struct.get(vulkan_10_physical_device_features$LAYOUT, vulkan_10_physical_device_features$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *vulkan_10_physical_device_features
     * }
     */
    public static void vulkan_10_physical_device_features(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(vulkan_10_physical_device_features$LAYOUT, vulkan_10_physical_device_features$OFFSET, fieldValue);
    }

    private static final OfInt device_extension_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("device_extension_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 device_extension_count
     * }
     */
    public static final OfInt device_extension_count$layout() {
        return device_extension_count$LAYOUT;
    }

    private static final long device_extension_count$OFFSET = $LAYOUT.byteOffset(groupElement("device_extension_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 device_extension_count
     * }
     */
    public static final long device_extension_count$offset() {
        return device_extension_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 device_extension_count
     * }
     */
    public static int device_extension_count(MemorySegment struct) {
        return struct.get(device_extension_count$LAYOUT, device_extension_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 device_extension_count
     * }
     */
    public static void device_extension_count(MemorySegment struct, int fieldValue) {
        struct.set(device_extension_count$LAYOUT, device_extension_count$OFFSET, fieldValue);
    }

    private static final AddressLayout device_extension_names$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("device_extension_names"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char **device_extension_names
     * }
     */
    public static final AddressLayout device_extension_names$layout() {
        return device_extension_names$LAYOUT;
    }

    private static final long device_extension_names$OFFSET = $LAYOUT.byteOffset(groupElement("device_extension_names"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char **device_extension_names
     * }
     */
    public static final long device_extension_names$offset() {
        return device_extension_names$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char **device_extension_names
     * }
     */
    public static MemorySegment device_extension_names(MemorySegment struct) {
        return struct.get(device_extension_names$LAYOUT, device_extension_names$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char **device_extension_names
     * }
     */
    public static void device_extension_names(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(device_extension_names$LAYOUT, device_extension_names$OFFSET, fieldValue);
    }

    private static final OfInt instance_extension_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("instance_extension_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 instance_extension_count
     * }
     */
    public static final OfInt instance_extension_count$layout() {
        return instance_extension_count$LAYOUT;
    }

    private static final long instance_extension_count$OFFSET = $LAYOUT.byteOffset(groupElement("instance_extension_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 instance_extension_count
     * }
     */
    public static final long instance_extension_count$offset() {
        return instance_extension_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 instance_extension_count
     * }
     */
    public static int instance_extension_count(MemorySegment struct) {
        return struct.get(instance_extension_count$LAYOUT, instance_extension_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 instance_extension_count
     * }
     */
    public static void instance_extension_count(MemorySegment struct, int fieldValue) {
        struct.set(instance_extension_count$LAYOUT, instance_extension_count$OFFSET, fieldValue);
    }

    private static final AddressLayout instance_extension_names$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("instance_extension_names"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char **instance_extension_names
     * }
     */
    public static final AddressLayout instance_extension_names$layout() {
        return instance_extension_names$LAYOUT;
    }

    private static final long instance_extension_names$OFFSET = $LAYOUT.byteOffset(groupElement("instance_extension_names"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char **instance_extension_names
     * }
     */
    public static final long instance_extension_names$offset() {
        return instance_extension_names$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char **instance_extension_names
     * }
     */
    public static MemorySegment instance_extension_names(MemorySegment struct) {
        return struct.get(instance_extension_names$LAYOUT, instance_extension_names$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char **instance_extension_names
     * }
     */
    public static void instance_extension_names(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(instance_extension_names$LAYOUT, instance_extension_names$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

