// Generated by jextract

package de.hpi.swa.trufflesqueak.shared.sdl.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_InitState {
 *     SDL_AtomicInt status;
 *     SDL_ThreadID thread;
 *     void *reserved;
 * }
 * }
 */
public class SDL_InitState {

    SDL_InitState() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_AtomicInt.layout().withName("status"),
        MemoryLayout.paddingLayout(4),
        SDL_h.C_LONG_LONG.withName("thread"),
        SDL_h.C_POINTER.withName("reserved")
    ).withName("SDL_InitState");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout status$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("status"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_AtomicInt status
     * }
     */
    public static final GroupLayout status$layout() {
        return status$LAYOUT;
    }

    private static final long status$OFFSET = $LAYOUT.byteOffset(groupElement("status"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_AtomicInt status
     * }
     */
    public static final long status$offset() {
        return status$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_AtomicInt status
     * }
     */
    public static MemorySegment status(MemorySegment struct) {
        return struct.asSlice(status$OFFSET, status$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_AtomicInt status
     * }
     */
    public static void status(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, status$OFFSET, status$LAYOUT.byteSize());
    }

    private static final OfLong thread$LAYOUT = (OfLong)$LAYOUT.select(groupElement("thread"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_ThreadID thread
     * }
     */
    public static final OfLong thread$layout() {
        return thread$LAYOUT;
    }

    private static final long thread$OFFSET = $LAYOUT.byteOffset(groupElement("thread"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_ThreadID thread
     * }
     */
    public static final long thread$offset() {
        return thread$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_ThreadID thread
     * }
     */
    public static long thread(MemorySegment struct) {
        return struct.get(thread$LAYOUT, thread$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_ThreadID thread
     * }
     */
    public static void thread(MemorySegment struct, long fieldValue) {
        struct.set(thread$LAYOUT, thread$OFFSET, fieldValue);
    }

    private static final AddressLayout reserved$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("reserved"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *reserved
     * }
     */
    public static final AddressLayout reserved$layout() {
        return reserved$LAYOUT;
    }

    private static final long reserved$OFFSET = $LAYOUT.byteOffset(groupElement("reserved"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *reserved
     * }
     */
    public static final long reserved$offset() {
        return reserved$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *reserved
     * }
     */
    public static MemorySegment reserved(MemorySegment struct) {
        return struct.get(reserved$LAYOUT, reserved$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *reserved
     * }
     */
    public static void reserved(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(reserved$LAYOUT, reserved$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

