// Generated by jextract

package de.hpi.swa.trufflesqueak.sdl3.bindings;

/**
 * {@snippet lang = c :
 * typedef struct _opaque_pthread_mutex_t {
 *     long __sig;
 *     char __opaque[56];
 * } __darwin_pthread_mutex_t
 * }
 */
public class __darwin_pthread_mutex_t extends _opaque_pthread_mutex_t {

    __darwin_pthread_mutex_t() {
        // Should not be called directly
    }
}
