// Generated by jextract

package de.hpi.swa.trufflesqueak.sdl3.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_Surface {
 *     SDL_SurfaceFlags flags;
 *     SDL_PixelFormat format;
 *     int w;
 *     int h;
 *     int pitch;
 *     void *pixels;
 *     int refcount;
 *     void *reserved;
 * }
 * }
 */
public class SDL_Surface {

    SDL_Surface() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_INT.withName("flags"),
        SDL_h.C_INT.withName("format"),
        SDL_h.C_INT.withName("w"),
        SDL_h.C_INT.withName("h"),
        SDL_h.C_INT.withName("pitch"),
        MemoryLayout.paddingLayout(4),
        SDL_h.C_POINTER.withName("pixels"),
        SDL_h.C_INT.withName("refcount"),
        MemoryLayout.paddingLayout(4),
        SDL_h.C_POINTER.withName("reserved")
    ).withName("SDL_Surface");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_SurfaceFlags flags
     * }
     */
    public static final OfInt flags$layout() {
        return flags$LAYOUT;
    }

    private static final long flags$OFFSET = $LAYOUT.byteOffset(groupElement("flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_SurfaceFlags flags
     * }
     */
    public static final long flags$offset() {
        return flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_SurfaceFlags flags
     * }
     */
    public static int flags(MemorySegment struct) {
        return struct.get(flags$LAYOUT, flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_SurfaceFlags flags
     * }
     */
    public static void flags(MemorySegment struct, int fieldValue) {
        struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
    }

    private static final OfInt format$LAYOUT = (OfInt)$LAYOUT.select(groupElement("format"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_PixelFormat format
     * }
     */
    public static final OfInt format$layout() {
        return format$LAYOUT;
    }

    private static final long format$OFFSET = $LAYOUT.byteOffset(groupElement("format"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_PixelFormat format
     * }
     */
    public static final long format$offset() {
        return format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_PixelFormat format
     * }
     */
    public static int format(MemorySegment struct) {
        return struct.get(format$LAYOUT, format$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_PixelFormat format
     * }
     */
    public static void format(MemorySegment struct, int fieldValue) {
        struct.set(format$LAYOUT, format$OFFSET, fieldValue);
    }

    private static final OfInt w$LAYOUT = (OfInt)$LAYOUT.select(groupElement("w"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int w
     * }
     */
    public static final OfInt w$layout() {
        return w$LAYOUT;
    }

    private static final long w$OFFSET = $LAYOUT.byteOffset(groupElement("w"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int w
     * }
     */
    public static final long w$offset() {
        return w$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int w
     * }
     */
    public static int w(MemorySegment struct) {
        return struct.get(w$LAYOUT, w$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int w
     * }
     */
    public static void w(MemorySegment struct, int fieldValue) {
        struct.set(w$LAYOUT, w$OFFSET, fieldValue);
    }

    private static final OfInt h$LAYOUT = (OfInt)$LAYOUT.select(groupElement("h"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int h
     * }
     */
    public static final OfInt h$layout() {
        return h$LAYOUT;
    }

    private static final long h$OFFSET = $LAYOUT.byteOffset(groupElement("h"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int h
     * }
     */
    public static final long h$offset() {
        return h$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int h
     * }
     */
    public static int h(MemorySegment struct) {
        return struct.get(h$LAYOUT, h$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int h
     * }
     */
    public static void h(MemorySegment struct, int fieldValue) {
        struct.set(h$LAYOUT, h$OFFSET, fieldValue);
    }

    private static final OfInt pitch$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pitch"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int pitch
     * }
     */
    public static final OfInt pitch$layout() {
        return pitch$LAYOUT;
    }

    private static final long pitch$OFFSET = $LAYOUT.byteOffset(groupElement("pitch"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int pitch
     * }
     */
    public static final long pitch$offset() {
        return pitch$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int pitch
     * }
     */
    public static int pitch(MemorySegment struct) {
        return struct.get(pitch$LAYOUT, pitch$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int pitch
     * }
     */
    public static void pitch(MemorySegment struct, int fieldValue) {
        struct.set(pitch$LAYOUT, pitch$OFFSET, fieldValue);
    }

    private static final AddressLayout pixels$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pixels"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *pixels
     * }
     */
    public static final AddressLayout pixels$layout() {
        return pixels$LAYOUT;
    }

    private static final long pixels$OFFSET = $LAYOUT.byteOffset(groupElement("pixels"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *pixels
     * }
     */
    public static final long pixels$offset() {
        return pixels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *pixels
     * }
     */
    public static MemorySegment pixels(MemorySegment struct) {
        return struct.get(pixels$LAYOUT, pixels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *pixels
     * }
     */
    public static void pixels(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pixels$LAYOUT, pixels$OFFSET, fieldValue);
    }

    private static final OfInt refcount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("refcount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int refcount
     * }
     */
    public static final OfInt refcount$layout() {
        return refcount$LAYOUT;
    }

    private static final long refcount$OFFSET = $LAYOUT.byteOffset(groupElement("refcount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int refcount
     * }
     */
    public static final long refcount$offset() {
        return refcount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int refcount
     * }
     */
    public static int refcount(MemorySegment struct) {
        return struct.get(refcount$LAYOUT, refcount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int refcount
     * }
     */
    public static void refcount(MemorySegment struct, int fieldValue) {
        struct.set(refcount$LAYOUT, refcount$OFFSET, fieldValue);
    }

    private static final AddressLayout reserved$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("reserved"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *reserved
     * }
     */
    public static final AddressLayout reserved$layout() {
        return reserved$LAYOUT;
    }

    private static final long reserved$OFFSET = $LAYOUT.byteOffset(groupElement("reserved"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *reserved
     * }
     */
    public static final long reserved$offset() {
        return reserved$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *reserved
     * }
     */
    public static MemorySegment reserved(MemorySegment struct) {
        return struct.get(reserved$LAYOUT, reserved$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *reserved
     * }
     */
    public static void reserved(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(reserved$LAYOUT, reserved$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

