// Generated by jextract

package de.hpi.swa.trufflesqueak.sdl3.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_Color {
 *     Uint8 r;
 *     Uint8 g;
 *     Uint8 b;
 *     Uint8 a;
 * }
 * }
 */
public class SDL_Color {

    SDL_Color() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_CHAR.withName("r"),
        SDL_h.C_CHAR.withName("g"),
        SDL_h.C_CHAR.withName("b"),
        SDL_h.C_CHAR.withName("a")
    ).withName("SDL_Color");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte r$LAYOUT = (OfByte)$LAYOUT.select(groupElement("r"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 r
     * }
     */
    public static final OfByte r$layout() {
        return r$LAYOUT;
    }

    private static final long r$OFFSET = $LAYOUT.byteOffset(groupElement("r"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 r
     * }
     */
    public static final long r$offset() {
        return r$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 r
     * }
     */
    public static byte r(MemorySegment struct) {
        return struct.get(r$LAYOUT, r$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 r
     * }
     */
    public static void r(MemorySegment struct, byte fieldValue) {
        struct.set(r$LAYOUT, r$OFFSET, fieldValue);
    }

    private static final OfByte g$LAYOUT = (OfByte)$LAYOUT.select(groupElement("g"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 g
     * }
     */
    public static final OfByte g$layout() {
        return g$LAYOUT;
    }

    private static final long g$OFFSET = $LAYOUT.byteOffset(groupElement("g"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 g
     * }
     */
    public static final long g$offset() {
        return g$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 g
     * }
     */
    public static byte g(MemorySegment struct) {
        return struct.get(g$LAYOUT, g$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 g
     * }
     */
    public static void g(MemorySegment struct, byte fieldValue) {
        struct.set(g$LAYOUT, g$OFFSET, fieldValue);
    }

    private static final OfByte b$LAYOUT = (OfByte)$LAYOUT.select(groupElement("b"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 b
     * }
     */
    public static final OfByte b$layout() {
        return b$LAYOUT;
    }

    private static final long b$OFFSET = $LAYOUT.byteOffset(groupElement("b"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 b
     * }
     */
    public static final long b$offset() {
        return b$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 b
     * }
     */
    public static byte b(MemorySegment struct) {
        return struct.get(b$LAYOUT, b$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 b
     * }
     */
    public static void b(MemorySegment struct, byte fieldValue) {
        struct.set(b$LAYOUT, b$OFFSET, fieldValue);
    }

    private static final OfByte a$LAYOUT = (OfByte)$LAYOUT.select(groupElement("a"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 a
     * }
     */
    public static final OfByte a$layout() {
        return a$LAYOUT;
    }

    private static final long a$OFFSET = $LAYOUT.byteOffset(groupElement("a"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 a
     * }
     */
    public static final long a$offset() {
        return a$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 a
     * }
     */
    public static byte a(MemorySegment struct) {
        return struct.get(a$LAYOUT, a$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 a
     * }
     */
    public static void a(MemorySegment struct, byte fieldValue) {
        struct.set(a$LAYOUT, a$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

