// Generated by jextract

package de.hpi.swa.trufflesqueak.sdl3.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_hid_device_info {
 *     char *path;
 *     unsigned short vendor_id;
 *     unsigned short product_id;
 *     wchar_t *serial_number;
 *     unsigned short release_number;
 *     wchar_t *manufacturer_string;
 *     wchar_t *product_string;
 *     unsigned short usage_page;
 *     unsigned short usage;
 *     int interface_number;
 *     int interface_class;
 *     int interface_subclass;
 *     int interface_protocol;
 *     SDL_hid_bus_type bus_type;
 *     struct SDL_hid_device_info *next;
 * }
 * }
 */
public class SDL_hid_device_info {

    SDL_hid_device_info() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_POINTER.withName("path"),
        SDL_h.C_SHORT.withName("vendor_id"),
        SDL_h.C_SHORT.withName("product_id"),
        MemoryLayout.paddingLayout(4),
        SDL_h.C_POINTER.withName("serial_number"),
        SDL_h.C_SHORT.withName("release_number"),
        MemoryLayout.paddingLayout(6),
        SDL_h.C_POINTER.withName("manufacturer_string"),
        SDL_h.C_POINTER.withName("product_string"),
        SDL_h.C_SHORT.withName("usage_page"),
        SDL_h.C_SHORT.withName("usage"),
        SDL_h.C_INT.withName("interface_number"),
        SDL_h.C_INT.withName("interface_class"),
        SDL_h.C_INT.withName("interface_subclass"),
        SDL_h.C_INT.withName("interface_protocol"),
        SDL_h.C_INT.withName("bus_type"),
        SDL_h.C_POINTER.withName("next")
    ).withName("SDL_hid_device_info");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout path$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("path"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *path
     * }
     */
    public static final AddressLayout path$layout() {
        return path$LAYOUT;
    }

    private static final long path$OFFSET = $LAYOUT.byteOffset(groupElement("path"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *path
     * }
     */
    public static final long path$offset() {
        return path$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *path
     * }
     */
    public static MemorySegment path(MemorySegment struct) {
        return struct.get(path$LAYOUT, path$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *path
     * }
     */
    public static void path(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(path$LAYOUT, path$OFFSET, fieldValue);
    }

    private static final OfShort vendor_id$LAYOUT = (OfShort)$LAYOUT.select(groupElement("vendor_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned short vendor_id
     * }
     */
    public static final OfShort vendor_id$layout() {
        return vendor_id$LAYOUT;
    }

    private static final long vendor_id$OFFSET = $LAYOUT.byteOffset(groupElement("vendor_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned short vendor_id
     * }
     */
    public static final long vendor_id$offset() {
        return vendor_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned short vendor_id
     * }
     */
    public static short vendor_id(MemorySegment struct) {
        return struct.get(vendor_id$LAYOUT, vendor_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned short vendor_id
     * }
     */
    public static void vendor_id(MemorySegment struct, short fieldValue) {
        struct.set(vendor_id$LAYOUT, vendor_id$OFFSET, fieldValue);
    }

    private static final OfShort product_id$LAYOUT = (OfShort)$LAYOUT.select(groupElement("product_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned short product_id
     * }
     */
    public static final OfShort product_id$layout() {
        return product_id$LAYOUT;
    }

    private static final long product_id$OFFSET = $LAYOUT.byteOffset(groupElement("product_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned short product_id
     * }
     */
    public static final long product_id$offset() {
        return product_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned short product_id
     * }
     */
    public static short product_id(MemorySegment struct) {
        return struct.get(product_id$LAYOUT, product_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned short product_id
     * }
     */
    public static void product_id(MemorySegment struct, short fieldValue) {
        struct.set(product_id$LAYOUT, product_id$OFFSET, fieldValue);
    }

    private static final AddressLayout serial_number$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("serial_number"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * wchar_t *serial_number
     * }
     */
    public static final AddressLayout serial_number$layout() {
        return serial_number$LAYOUT;
    }

    private static final long serial_number$OFFSET = $LAYOUT.byteOffset(groupElement("serial_number"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * wchar_t *serial_number
     * }
     */
    public static final long serial_number$offset() {
        return serial_number$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * wchar_t *serial_number
     * }
     */
    public static MemorySegment serial_number(MemorySegment struct) {
        return struct.get(serial_number$LAYOUT, serial_number$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * wchar_t *serial_number
     * }
     */
    public static void serial_number(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(serial_number$LAYOUT, serial_number$OFFSET, fieldValue);
    }

    private static final OfShort release_number$LAYOUT = (OfShort)$LAYOUT.select(groupElement("release_number"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned short release_number
     * }
     */
    public static final OfShort release_number$layout() {
        return release_number$LAYOUT;
    }

    private static final long release_number$OFFSET = $LAYOUT.byteOffset(groupElement("release_number"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned short release_number
     * }
     */
    public static final long release_number$offset() {
        return release_number$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned short release_number
     * }
     */
    public static short release_number(MemorySegment struct) {
        return struct.get(release_number$LAYOUT, release_number$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned short release_number
     * }
     */
    public static void release_number(MemorySegment struct, short fieldValue) {
        struct.set(release_number$LAYOUT, release_number$OFFSET, fieldValue);
    }

    private static final AddressLayout manufacturer_string$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("manufacturer_string"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * wchar_t *manufacturer_string
     * }
     */
    public static final AddressLayout manufacturer_string$layout() {
        return manufacturer_string$LAYOUT;
    }

    private static final long manufacturer_string$OFFSET = $LAYOUT.byteOffset(groupElement("manufacturer_string"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * wchar_t *manufacturer_string
     * }
     */
    public static final long manufacturer_string$offset() {
        return manufacturer_string$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * wchar_t *manufacturer_string
     * }
     */
    public static MemorySegment manufacturer_string(MemorySegment struct) {
        return struct.get(manufacturer_string$LAYOUT, manufacturer_string$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * wchar_t *manufacturer_string
     * }
     */
    public static void manufacturer_string(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(manufacturer_string$LAYOUT, manufacturer_string$OFFSET, fieldValue);
    }

    private static final AddressLayout product_string$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("product_string"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * wchar_t *product_string
     * }
     */
    public static final AddressLayout product_string$layout() {
        return product_string$LAYOUT;
    }

    private static final long product_string$OFFSET = $LAYOUT.byteOffset(groupElement("product_string"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * wchar_t *product_string
     * }
     */
    public static final long product_string$offset() {
        return product_string$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * wchar_t *product_string
     * }
     */
    public static MemorySegment product_string(MemorySegment struct) {
        return struct.get(product_string$LAYOUT, product_string$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * wchar_t *product_string
     * }
     */
    public static void product_string(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(product_string$LAYOUT, product_string$OFFSET, fieldValue);
    }

    private static final OfShort usage_page$LAYOUT = (OfShort)$LAYOUT.select(groupElement("usage_page"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned short usage_page
     * }
     */
    public static final OfShort usage_page$layout() {
        return usage_page$LAYOUT;
    }

    private static final long usage_page$OFFSET = $LAYOUT.byteOffset(groupElement("usage_page"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned short usage_page
     * }
     */
    public static final long usage_page$offset() {
        return usage_page$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned short usage_page
     * }
     */
    public static short usage_page(MemorySegment struct) {
        return struct.get(usage_page$LAYOUT, usage_page$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned short usage_page
     * }
     */
    public static void usage_page(MemorySegment struct, short fieldValue) {
        struct.set(usage_page$LAYOUT, usage_page$OFFSET, fieldValue);
    }

    private static final OfShort usage$LAYOUT = (OfShort)$LAYOUT.select(groupElement("usage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned short usage
     * }
     */
    public static final OfShort usage$layout() {
        return usage$LAYOUT;
    }

    private static final long usage$OFFSET = $LAYOUT.byteOffset(groupElement("usage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned short usage
     * }
     */
    public static final long usage$offset() {
        return usage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned short usage
     * }
     */
    public static short usage(MemorySegment struct) {
        return struct.get(usage$LAYOUT, usage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned short usage
     * }
     */
    public static void usage(MemorySegment struct, short fieldValue) {
        struct.set(usage$LAYOUT, usage$OFFSET, fieldValue);
    }

    private static final OfInt interface_number$LAYOUT = (OfInt)$LAYOUT.select(groupElement("interface_number"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int interface_number
     * }
     */
    public static final OfInt interface_number$layout() {
        return interface_number$LAYOUT;
    }

    private static final long interface_number$OFFSET = $LAYOUT.byteOffset(groupElement("interface_number"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int interface_number
     * }
     */
    public static final long interface_number$offset() {
        return interface_number$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int interface_number
     * }
     */
    public static int interface_number(MemorySegment struct) {
        return struct.get(interface_number$LAYOUT, interface_number$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int interface_number
     * }
     */
    public static void interface_number(MemorySegment struct, int fieldValue) {
        struct.set(interface_number$LAYOUT, interface_number$OFFSET, fieldValue);
    }

    private static final OfInt interface_class$LAYOUT = (OfInt)$LAYOUT.select(groupElement("interface_class"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int interface_class
     * }
     */
    public static final OfInt interface_class$layout() {
        return interface_class$LAYOUT;
    }

    private static final long interface_class$OFFSET = $LAYOUT.byteOffset(groupElement("interface_class"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int interface_class
     * }
     */
    public static final long interface_class$offset() {
        return interface_class$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int interface_class
     * }
     */
    public static int interface_class(MemorySegment struct) {
        return struct.get(interface_class$LAYOUT, interface_class$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int interface_class
     * }
     */
    public static void interface_class(MemorySegment struct, int fieldValue) {
        struct.set(interface_class$LAYOUT, interface_class$OFFSET, fieldValue);
    }

    private static final OfInt interface_subclass$LAYOUT = (OfInt)$LAYOUT.select(groupElement("interface_subclass"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int interface_subclass
     * }
     */
    public static final OfInt interface_subclass$layout() {
        return interface_subclass$LAYOUT;
    }

    private static final long interface_subclass$OFFSET = $LAYOUT.byteOffset(groupElement("interface_subclass"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int interface_subclass
     * }
     */
    public static final long interface_subclass$offset() {
        return interface_subclass$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int interface_subclass
     * }
     */
    public static int interface_subclass(MemorySegment struct) {
        return struct.get(interface_subclass$LAYOUT, interface_subclass$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int interface_subclass
     * }
     */
    public static void interface_subclass(MemorySegment struct, int fieldValue) {
        struct.set(interface_subclass$LAYOUT, interface_subclass$OFFSET, fieldValue);
    }

    private static final OfInt interface_protocol$LAYOUT = (OfInt)$LAYOUT.select(groupElement("interface_protocol"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int interface_protocol
     * }
     */
    public static final OfInt interface_protocol$layout() {
        return interface_protocol$LAYOUT;
    }

    private static final long interface_protocol$OFFSET = $LAYOUT.byteOffset(groupElement("interface_protocol"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int interface_protocol
     * }
     */
    public static final long interface_protocol$offset() {
        return interface_protocol$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int interface_protocol
     * }
     */
    public static int interface_protocol(MemorySegment struct) {
        return struct.get(interface_protocol$LAYOUT, interface_protocol$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int interface_protocol
     * }
     */
    public static void interface_protocol(MemorySegment struct, int fieldValue) {
        struct.set(interface_protocol$LAYOUT, interface_protocol$OFFSET, fieldValue);
    }

    private static final OfInt bus_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bus_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_hid_bus_type bus_type
     * }
     */
    public static final OfInt bus_type$layout() {
        return bus_type$LAYOUT;
    }

    private static final long bus_type$OFFSET = $LAYOUT.byteOffset(groupElement("bus_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_hid_bus_type bus_type
     * }
     */
    public static final long bus_type$offset() {
        return bus_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_hid_bus_type bus_type
     * }
     */
    public static int bus_type(MemorySegment struct) {
        return struct.get(bus_type$LAYOUT, bus_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_hid_bus_type bus_type
     * }
     */
    public static void bus_type(MemorySegment struct, int fieldValue) {
        struct.set(bus_type$LAYOUT, bus_type$OFFSET, fieldValue);
    }

    private static final AddressLayout next$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("next"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct SDL_hid_device_info *next
     * }
     */
    public static final AddressLayout next$layout() {
        return next$LAYOUT;
    }

    private static final long next$OFFSET = $LAYOUT.byteOffset(groupElement("next"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct SDL_hid_device_info *next
     * }
     */
    public static final long next$offset() {
        return next$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct SDL_hid_device_info *next
     * }
     */
    public static MemorySegment next(MemorySegment struct) {
        return struct.get(next$LAYOUT, next$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct SDL_hid_device_info *next
     * }
     */
    public static void next(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(next$LAYOUT, next$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

