// Generated by jextract

package de.hpi.swa.trufflesqueak.sdl3.bindings;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang = c :
 * struct SDL_FRect {
 *     float x;
 *     float y;
 *     float w;
 *     float h;
 * }
 * }
 */
public class SDL_FRect {

    SDL_FRect() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
                    SDL_h.C_FLOAT.withName("x"),
                    SDL_h.C_FLOAT.withName("y"),
                    SDL_h.C_FLOAT.withName("w"),
                    SDL_h.C_FLOAT.withName("h")).withName("SDL_FRect");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfFloat x$LAYOUT = (OfFloat) $LAYOUT.select(groupElement("x"));

    /**
     * Layout for field:
     * {@snippet lang = c : * float x
     * }
     */
    public static final OfFloat x$layout() {
        return x$LAYOUT;
    }

    private static final long x$OFFSET = $LAYOUT.byteOffset(groupElement("x"));

    /**
     * Offset for field:
     * {@snippet lang = c : * float x
     * }
     */
    public static final long x$offset() {
        return x$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c : * float x
     * }
     */
    public static float x(MemorySegment struct) {
        return struct.get(x$LAYOUT, x$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c : * float x
     * }
     */
    public static void x(MemorySegment struct, float fieldValue) {
        struct.set(x$LAYOUT, x$OFFSET, fieldValue);
    }

    private static final OfFloat y$LAYOUT = (OfFloat) $LAYOUT.select(groupElement("y"));

    /**
     * Layout for field:
     * {@snippet lang = c : * float y
     * }
     */
    public static final OfFloat y$layout() {
        return y$LAYOUT;
    }

    private static final long y$OFFSET = $LAYOUT.byteOffset(groupElement("y"));

    /**
     * Offset for field:
     * {@snippet lang = c : * float y
     * }
     */
    public static final long y$offset() {
        return y$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c : * float y
     * }
     */
    public static float y(MemorySegment struct) {
        return struct.get(y$LAYOUT, y$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c : * float y
     * }
     */
    public static void y(MemorySegment struct, float fieldValue) {
        struct.set(y$LAYOUT, y$OFFSET, fieldValue);
    }

    private static final OfFloat w$LAYOUT = (OfFloat) $LAYOUT.select(groupElement("w"));

    /**
     * Layout for field:
     * {@snippet lang = c : * float w
     * }
     */
    public static final OfFloat w$layout() {
        return w$LAYOUT;
    }

    private static final long w$OFFSET = $LAYOUT.byteOffset(groupElement("w"));

    /**
     * Offset for field:
     * {@snippet lang = c : * float w
     * }
     */
    public static final long w$offset() {
        return w$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c : * float w
     * }
     */
    public static float w(MemorySegment struct) {
        return struct.get(w$LAYOUT, w$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c : * float w
     * }
     */
    public static void w(MemorySegment struct, float fieldValue) {
        struct.set(w$LAYOUT, w$OFFSET, fieldValue);
    }

    private static final OfFloat h$LAYOUT = (OfFloat) $LAYOUT.select(groupElement("h"));

    /**
     * Layout for field:
     * {@snippet lang = c : * float h
     * }
     */
    public static final OfFloat h$layout() {
        return h$LAYOUT;
    }

    private static final long h$OFFSET = $LAYOUT.byteOffset(groupElement("h"));

    /**
     * Offset for field:
     * {@snippet lang = c : * float h
     * }
     */
    public static final long h$offset() {
        return h$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c : * float h
     * }
     */
    public static float h(MemorySegment struct) {
        return struct.get(h$LAYOUT, h$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c : * float h
     * }
     */
    public static void h(MemorySegment struct, float fieldValue) {
        struct.set(h$LAYOUT, h$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The
     * returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() {
        return layout().byteSize();
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment
     * has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The
     * returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The
     * returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}
