// Generated by jextract

package de.hpi.swa.trufflesqueak.sdl3.bindings;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang = c :
 * struct SDL_GPUColorTargetDescription {
 *     SDL_GPUTextureFormat format;
 *     SDL_GPUColorTargetBlendState blend_state;
 * }
 * }
 */
public class SDL_GPUColorTargetDescription {

    SDL_GPUColorTargetDescription() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
                    SDL_h.C_INT.withName("format"),
                    SDL_GPUColorTargetBlendState.layout().withName("blend_state")).withName("SDL_GPUColorTargetDescription");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt format$LAYOUT = (OfInt) $LAYOUT.select(groupElement("format"));

    /**
     * Layout for field:
     * {@snippet lang = c : * SDL_GPUTextureFormat format
     * }
     */
    public static final OfInt format$layout() {
        return format$LAYOUT;
    }

    private static final long format$OFFSET = $LAYOUT.byteOffset(groupElement("format"));

    /**
     * Offset for field:
     * {@snippet lang = c : * SDL_GPUTextureFormat format
     * }
     */
    public static final long format$offset() {
        return format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c : * SDL_GPUTextureFormat format
     * }
     */
    public static int format(MemorySegment struct) {
        return struct.get(format$LAYOUT, format$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c : * SDL_GPUTextureFormat format
     * }
     */
    public static void format(MemorySegment struct, int fieldValue) {
        struct.set(format$LAYOUT, format$OFFSET, fieldValue);
    }

    private static final GroupLayout blend_state$LAYOUT = (GroupLayout) $LAYOUT.select(groupElement("blend_state"));

    /**
     * Layout for field:
     * {@snippet lang = c : * SDL_GPUColorTargetBlendState blend_state
     * }
     */
    public static final GroupLayout blend_state$layout() {
        return blend_state$LAYOUT;
    }

    private static final long blend_state$OFFSET = $LAYOUT.byteOffset(groupElement("blend_state"));

    /**
     * Offset for field:
     * {@snippet lang = c : * SDL_GPUColorTargetBlendState blend_state
     * }
     */
    public static final long blend_state$offset() {
        return blend_state$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c : * SDL_GPUColorTargetBlendState blend_state
     * }
     */
    public static MemorySegment blend_state(MemorySegment struct) {
        return struct.asSlice(blend_state$OFFSET, blend_state$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang = c : * SDL_GPUColorTargetBlendState blend_state
     * }
     */
    public static void blend_state(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, blend_state$OFFSET, blend_state$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}. The
     * returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() {
        return layout().byteSize();
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}. The returned segment
     * has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The
     * returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any). The
     * returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}
