// Generated by jextract

package de.hpi.swa.trufflesqueak.sdl3.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;

/**
 * {@snippet lang = c : * typedef SDL_AppResult (*SDL_AppInit_func)(void **, int, char **)
 * }
 */
public final class SDL_AppInit_func {

    private SDL_AppInit_func() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment appstate, int argc, MemorySegment argv);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
                    SDL_h.C_INT,
                    SDL_h.C_POINTER,
                    SDL_h.C_INT,
                    SDL_h.C_POINTER);

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = SDL_h.upcallHandle(SDL_AppInit_func.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}. The lifetime of
     * the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(SDL_AppInit_func.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr, MemorySegment appstate, int argc, MemorySegment argv) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, appstate, argc, argv);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
