// Generated by jextract

package de.hpi.swa.trufflesqueak.sdl3.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_DisplayMode {
 *     SDL_DisplayID displayID;
 *     SDL_PixelFormat format;
 *     int w;
 *     int h;
 *     float pixel_density;
 *     float refresh_rate;
 *     int refresh_rate_numerator;
 *     int refresh_rate_denominator;
 *     SDL_DisplayModeData *internal;
 * }
 * }
 */
public class SDL_DisplayMode {

    SDL_DisplayMode() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_INT.withName("displayID"),
        SDL_h.C_INT.withName("format"),
        SDL_h.C_INT.withName("w"),
        SDL_h.C_INT.withName("h"),
        SDL_h.C_FLOAT.withName("pixel_density"),
        SDL_h.C_FLOAT.withName("refresh_rate"),
        SDL_h.C_INT.withName("refresh_rate_numerator"),
        SDL_h.C_INT.withName("refresh_rate_denominator"),
        SDL_h.C_POINTER.withName("internal")
    ).withName("SDL_DisplayMode");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt displayID$LAYOUT = (OfInt)$LAYOUT.select(groupElement("displayID"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_DisplayID displayID
     * }
     */
    public static final OfInt displayID$layout() {
        return displayID$LAYOUT;
    }

    private static final long displayID$OFFSET = $LAYOUT.byteOffset(groupElement("displayID"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_DisplayID displayID
     * }
     */
    public static final long displayID$offset() {
        return displayID$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_DisplayID displayID
     * }
     */
    public static int displayID(MemorySegment struct) {
        return struct.get(displayID$LAYOUT, displayID$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_DisplayID displayID
     * }
     */
    public static void displayID(MemorySegment struct, int fieldValue) {
        struct.set(displayID$LAYOUT, displayID$OFFSET, fieldValue);
    }

    private static final OfInt format$LAYOUT = (OfInt)$LAYOUT.select(groupElement("format"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_PixelFormat format
     * }
     */
    public static final OfInt format$layout() {
        return format$LAYOUT;
    }

    private static final long format$OFFSET = $LAYOUT.byteOffset(groupElement("format"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_PixelFormat format
     * }
     */
    public static final long format$offset() {
        return format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_PixelFormat format
     * }
     */
    public static int format(MemorySegment struct) {
        return struct.get(format$LAYOUT, format$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_PixelFormat format
     * }
     */
    public static void format(MemorySegment struct, int fieldValue) {
        struct.set(format$LAYOUT, format$OFFSET, fieldValue);
    }

    private static final OfInt w$LAYOUT = (OfInt)$LAYOUT.select(groupElement("w"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int w
     * }
     */
    public static final OfInt w$layout() {
        return w$LAYOUT;
    }

    private static final long w$OFFSET = $LAYOUT.byteOffset(groupElement("w"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int w
     * }
     */
    public static final long w$offset() {
        return w$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int w
     * }
     */
    public static int w(MemorySegment struct) {
        return struct.get(w$LAYOUT, w$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int w
     * }
     */
    public static void w(MemorySegment struct, int fieldValue) {
        struct.set(w$LAYOUT, w$OFFSET, fieldValue);
    }

    private static final OfInt h$LAYOUT = (OfInt)$LAYOUT.select(groupElement("h"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int h
     * }
     */
    public static final OfInt h$layout() {
        return h$LAYOUT;
    }

    private static final long h$OFFSET = $LAYOUT.byteOffset(groupElement("h"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int h
     * }
     */
    public static final long h$offset() {
        return h$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int h
     * }
     */
    public static int h(MemorySegment struct) {
        return struct.get(h$LAYOUT, h$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int h
     * }
     */
    public static void h(MemorySegment struct, int fieldValue) {
        struct.set(h$LAYOUT, h$OFFSET, fieldValue);
    }

    private static final OfFloat pixel_density$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("pixel_density"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float pixel_density
     * }
     */
    public static final OfFloat pixel_density$layout() {
        return pixel_density$LAYOUT;
    }

    private static final long pixel_density$OFFSET = $LAYOUT.byteOffset(groupElement("pixel_density"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float pixel_density
     * }
     */
    public static final long pixel_density$offset() {
        return pixel_density$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float pixel_density
     * }
     */
    public static float pixel_density(MemorySegment struct) {
        return struct.get(pixel_density$LAYOUT, pixel_density$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float pixel_density
     * }
     */
    public static void pixel_density(MemorySegment struct, float fieldValue) {
        struct.set(pixel_density$LAYOUT, pixel_density$OFFSET, fieldValue);
    }

    private static final OfFloat refresh_rate$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("refresh_rate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float refresh_rate
     * }
     */
    public static final OfFloat refresh_rate$layout() {
        return refresh_rate$LAYOUT;
    }

    private static final long refresh_rate$OFFSET = $LAYOUT.byteOffset(groupElement("refresh_rate"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float refresh_rate
     * }
     */
    public static final long refresh_rate$offset() {
        return refresh_rate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float refresh_rate
     * }
     */
    public static float refresh_rate(MemorySegment struct) {
        return struct.get(refresh_rate$LAYOUT, refresh_rate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float refresh_rate
     * }
     */
    public static void refresh_rate(MemorySegment struct, float fieldValue) {
        struct.set(refresh_rate$LAYOUT, refresh_rate$OFFSET, fieldValue);
    }

    private static final OfInt refresh_rate_numerator$LAYOUT = (OfInt)$LAYOUT.select(groupElement("refresh_rate_numerator"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int refresh_rate_numerator
     * }
     */
    public static final OfInt refresh_rate_numerator$layout() {
        return refresh_rate_numerator$LAYOUT;
    }

    private static final long refresh_rate_numerator$OFFSET = $LAYOUT.byteOffset(groupElement("refresh_rate_numerator"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int refresh_rate_numerator
     * }
     */
    public static final long refresh_rate_numerator$offset() {
        return refresh_rate_numerator$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int refresh_rate_numerator
     * }
     */
    public static int refresh_rate_numerator(MemorySegment struct) {
        return struct.get(refresh_rate_numerator$LAYOUT, refresh_rate_numerator$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int refresh_rate_numerator
     * }
     */
    public static void refresh_rate_numerator(MemorySegment struct, int fieldValue) {
        struct.set(refresh_rate_numerator$LAYOUT, refresh_rate_numerator$OFFSET, fieldValue);
    }

    private static final OfInt refresh_rate_denominator$LAYOUT = (OfInt)$LAYOUT.select(groupElement("refresh_rate_denominator"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int refresh_rate_denominator
     * }
     */
    public static final OfInt refresh_rate_denominator$layout() {
        return refresh_rate_denominator$LAYOUT;
    }

    private static final long refresh_rate_denominator$OFFSET = $LAYOUT.byteOffset(groupElement("refresh_rate_denominator"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int refresh_rate_denominator
     * }
     */
    public static final long refresh_rate_denominator$offset() {
        return refresh_rate_denominator$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int refresh_rate_denominator
     * }
     */
    public static int refresh_rate_denominator(MemorySegment struct) {
        return struct.get(refresh_rate_denominator$LAYOUT, refresh_rate_denominator$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int refresh_rate_denominator
     * }
     */
    public static void refresh_rate_denominator(MemorySegment struct, int fieldValue) {
        struct.set(refresh_rate_denominator$LAYOUT, refresh_rate_denominator$OFFSET, fieldValue);
    }

    private static final AddressLayout internal$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("internal"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_DisplayModeData *internal
     * }
     */
    public static final AddressLayout internal$layout() {
        return internal$LAYOUT;
    }

    private static final long internal$OFFSET = $LAYOUT.byteOffset(groupElement("internal"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_DisplayModeData *internal
     * }
     */
    public static final long internal$offset() {
        return internal$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_DisplayModeData *internal
     * }
     */
    public static MemorySegment internal(MemorySegment struct) {
        return struct.get(internal$LAYOUT, internal$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_DisplayModeData *internal
     * }
     */
    public static void internal(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(internal$LAYOUT, internal$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

