// Generated by jextract

package de.hpi.swa.trufflesqueak.sdl3.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_GPUGraphicsPipelineTargetInfo {
 *     const SDL_GPUColorTargetDescription *color_target_descriptions;
 *     Uint32 num_color_targets;
 *     SDL_GPUTextureFormat depth_stencil_format;
 *     bool has_depth_stencil_target;
 *     Uint8 padding1;
 *     Uint8 padding2;
 *     Uint8 padding3;
 * }
 * }
 */
public class SDL_GPUGraphicsPipelineTargetInfo {

    SDL_GPUGraphicsPipelineTargetInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_POINTER.withName("color_target_descriptions"),
        SDL_h.C_INT.withName("num_color_targets"),
        SDL_h.C_INT.withName("depth_stencil_format"),
        SDL_h.C_BOOL.withName("has_depth_stencil_target"),
        SDL_h.C_CHAR.withName("padding1"),
        SDL_h.C_CHAR.withName("padding2"),
        SDL_h.C_CHAR.withName("padding3"),
        MemoryLayout.paddingLayout(4)
    ).withName("SDL_GPUGraphicsPipelineTargetInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout color_target_descriptions$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("color_target_descriptions"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const SDL_GPUColorTargetDescription *color_target_descriptions
     * }
     */
    public static final AddressLayout color_target_descriptions$layout() {
        return color_target_descriptions$LAYOUT;
    }

    private static final long color_target_descriptions$OFFSET = $LAYOUT.byteOffset(groupElement("color_target_descriptions"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const SDL_GPUColorTargetDescription *color_target_descriptions
     * }
     */
    public static final long color_target_descriptions$offset() {
        return color_target_descriptions$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const SDL_GPUColorTargetDescription *color_target_descriptions
     * }
     */
    public static MemorySegment color_target_descriptions(MemorySegment struct) {
        return struct.get(color_target_descriptions$LAYOUT, color_target_descriptions$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const SDL_GPUColorTargetDescription *color_target_descriptions
     * }
     */
    public static void color_target_descriptions(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(color_target_descriptions$LAYOUT, color_target_descriptions$OFFSET, fieldValue);
    }

    private static final OfInt num_color_targets$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_color_targets"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 num_color_targets
     * }
     */
    public static final OfInt num_color_targets$layout() {
        return num_color_targets$LAYOUT;
    }

    private static final long num_color_targets$OFFSET = $LAYOUT.byteOffset(groupElement("num_color_targets"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 num_color_targets
     * }
     */
    public static final long num_color_targets$offset() {
        return num_color_targets$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 num_color_targets
     * }
     */
    public static int num_color_targets(MemorySegment struct) {
        return struct.get(num_color_targets$LAYOUT, num_color_targets$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 num_color_targets
     * }
     */
    public static void num_color_targets(MemorySegment struct, int fieldValue) {
        struct.set(num_color_targets$LAYOUT, num_color_targets$OFFSET, fieldValue);
    }

    private static final OfInt depth_stencil_format$LAYOUT = (OfInt)$LAYOUT.select(groupElement("depth_stencil_format"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUTextureFormat depth_stencil_format
     * }
     */
    public static final OfInt depth_stencil_format$layout() {
        return depth_stencil_format$LAYOUT;
    }

    private static final long depth_stencil_format$OFFSET = $LAYOUT.byteOffset(groupElement("depth_stencil_format"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUTextureFormat depth_stencil_format
     * }
     */
    public static final long depth_stencil_format$offset() {
        return depth_stencil_format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUTextureFormat depth_stencil_format
     * }
     */
    public static int depth_stencil_format(MemorySegment struct) {
        return struct.get(depth_stencil_format$LAYOUT, depth_stencil_format$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUTextureFormat depth_stencil_format
     * }
     */
    public static void depth_stencil_format(MemorySegment struct, int fieldValue) {
        struct.set(depth_stencil_format$LAYOUT, depth_stencil_format$OFFSET, fieldValue);
    }

    private static final OfBoolean has_depth_stencil_target$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("has_depth_stencil_target"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool has_depth_stencil_target
     * }
     */
    public static final OfBoolean has_depth_stencil_target$layout() {
        return has_depth_stencil_target$LAYOUT;
    }

    private static final long has_depth_stencil_target$OFFSET = $LAYOUT.byteOffset(groupElement("has_depth_stencil_target"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool has_depth_stencil_target
     * }
     */
    public static final long has_depth_stencil_target$offset() {
        return has_depth_stencil_target$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool has_depth_stencil_target
     * }
     */
    public static boolean has_depth_stencil_target(MemorySegment struct) {
        return struct.get(has_depth_stencil_target$LAYOUT, has_depth_stencil_target$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool has_depth_stencil_target
     * }
     */
    public static void has_depth_stencil_target(MemorySegment struct, boolean fieldValue) {
        struct.set(has_depth_stencil_target$LAYOUT, has_depth_stencil_target$OFFSET, fieldValue);
    }

    private static final OfByte padding1$LAYOUT = (OfByte)$LAYOUT.select(groupElement("padding1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static final OfByte padding1$layout() {
        return padding1$LAYOUT;
    }

    private static final long padding1$OFFSET = $LAYOUT.byteOffset(groupElement("padding1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static final long padding1$offset() {
        return padding1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static byte padding1(MemorySegment struct) {
        return struct.get(padding1$LAYOUT, padding1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static void padding1(MemorySegment struct, byte fieldValue) {
        struct.set(padding1$LAYOUT, padding1$OFFSET, fieldValue);
    }

    private static final OfByte padding2$LAYOUT = (OfByte)$LAYOUT.select(groupElement("padding2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static final OfByte padding2$layout() {
        return padding2$LAYOUT;
    }

    private static final long padding2$OFFSET = $LAYOUT.byteOffset(groupElement("padding2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static final long padding2$offset() {
        return padding2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static byte padding2(MemorySegment struct) {
        return struct.get(padding2$LAYOUT, padding2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static void padding2(MemorySegment struct, byte fieldValue) {
        struct.set(padding2$LAYOUT, padding2$OFFSET, fieldValue);
    }

    private static final OfByte padding3$LAYOUT = (OfByte)$LAYOUT.select(groupElement("padding3"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static final OfByte padding3$layout() {
        return padding3$LAYOUT;
    }

    private static final long padding3$OFFSET = $LAYOUT.byteOffset(groupElement("padding3"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static final long padding3$offset() {
        return padding3$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static byte padding3(MemorySegment struct) {
        return struct.get(padding3$LAYOUT, padding3$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static void padding3(MemorySegment struct, byte fieldValue) {
        struct.set(padding3$LAYOUT, padding3$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

