// Generated by jextract

package de.hpi.swa.trufflesqueak.sdl3.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_GPUVertexInputState {
 *     const SDL_GPUVertexBufferDescription *vertex_buffer_descriptions;
 *     Uint32 num_vertex_buffers;
 *     const SDL_GPUVertexAttribute *vertex_attributes;
 *     Uint32 num_vertex_attributes;
 * }
 * }
 */
public class SDL_GPUVertexInputState {

    SDL_GPUVertexInputState() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_POINTER.withName("vertex_buffer_descriptions"),
        SDL_h.C_INT.withName("num_vertex_buffers"),
        MemoryLayout.paddingLayout(4),
        SDL_h.C_POINTER.withName("vertex_attributes"),
        SDL_h.C_INT.withName("num_vertex_attributes"),
        MemoryLayout.paddingLayout(4)
    ).withName("SDL_GPUVertexInputState");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout vertex_buffer_descriptions$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("vertex_buffer_descriptions"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const SDL_GPUVertexBufferDescription *vertex_buffer_descriptions
     * }
     */
    public static final AddressLayout vertex_buffer_descriptions$layout() {
        return vertex_buffer_descriptions$LAYOUT;
    }

    private static final long vertex_buffer_descriptions$OFFSET = $LAYOUT.byteOffset(groupElement("vertex_buffer_descriptions"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const SDL_GPUVertexBufferDescription *vertex_buffer_descriptions
     * }
     */
    public static final long vertex_buffer_descriptions$offset() {
        return vertex_buffer_descriptions$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const SDL_GPUVertexBufferDescription *vertex_buffer_descriptions
     * }
     */
    public static MemorySegment vertex_buffer_descriptions(MemorySegment struct) {
        return struct.get(vertex_buffer_descriptions$LAYOUT, vertex_buffer_descriptions$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const SDL_GPUVertexBufferDescription *vertex_buffer_descriptions
     * }
     */
    public static void vertex_buffer_descriptions(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(vertex_buffer_descriptions$LAYOUT, vertex_buffer_descriptions$OFFSET, fieldValue);
    }

    private static final OfInt num_vertex_buffers$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_vertex_buffers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 num_vertex_buffers
     * }
     */
    public static final OfInt num_vertex_buffers$layout() {
        return num_vertex_buffers$LAYOUT;
    }

    private static final long num_vertex_buffers$OFFSET = $LAYOUT.byteOffset(groupElement("num_vertex_buffers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 num_vertex_buffers
     * }
     */
    public static final long num_vertex_buffers$offset() {
        return num_vertex_buffers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 num_vertex_buffers
     * }
     */
    public static int num_vertex_buffers(MemorySegment struct) {
        return struct.get(num_vertex_buffers$LAYOUT, num_vertex_buffers$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 num_vertex_buffers
     * }
     */
    public static void num_vertex_buffers(MemorySegment struct, int fieldValue) {
        struct.set(num_vertex_buffers$LAYOUT, num_vertex_buffers$OFFSET, fieldValue);
    }

    private static final AddressLayout vertex_attributes$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("vertex_attributes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const SDL_GPUVertexAttribute *vertex_attributes
     * }
     */
    public static final AddressLayout vertex_attributes$layout() {
        return vertex_attributes$LAYOUT;
    }

    private static final long vertex_attributes$OFFSET = $LAYOUT.byteOffset(groupElement("vertex_attributes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const SDL_GPUVertexAttribute *vertex_attributes
     * }
     */
    public static final long vertex_attributes$offset() {
        return vertex_attributes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const SDL_GPUVertexAttribute *vertex_attributes
     * }
     */
    public static MemorySegment vertex_attributes(MemorySegment struct) {
        return struct.get(vertex_attributes$LAYOUT, vertex_attributes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const SDL_GPUVertexAttribute *vertex_attributes
     * }
     */
    public static void vertex_attributes(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(vertex_attributes$LAYOUT, vertex_attributes$OFFSET, fieldValue);
    }

    private static final OfInt num_vertex_attributes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_vertex_attributes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 num_vertex_attributes
     * }
     */
    public static final OfInt num_vertex_attributes$layout() {
        return num_vertex_attributes$LAYOUT;
    }

    private static final long num_vertex_attributes$OFFSET = $LAYOUT.byteOffset(groupElement("num_vertex_attributes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 num_vertex_attributes
     * }
     */
    public static final long num_vertex_attributes$offset() {
        return num_vertex_attributes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 num_vertex_attributes
     * }
     */
    public static int num_vertex_attributes(MemorySegment struct) {
        return struct.get(num_vertex_attributes$LAYOUT, num_vertex_attributes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 num_vertex_attributes
     * }
     */
    public static void num_vertex_attributes(MemorySegment struct, int fieldValue) {
        struct.set(num_vertex_attributes$LAYOUT, num_vertex_attributes$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

