world menu
adjustDoMenu
	Utilities initializeCommonRequestStrings.
	Utilities commonRequestStrings:
'ToolSet browseClass: Polyglot class category: ''polyglot-api''.
ToolSet browseClass: Interop class.
-
Polyglot toggleEmphasizeInterop.
-
Graal runtime inspect.
-
RPlotMorph example.
-
TruffleSqueakUtilities setUpImage.
TruffleSqueakUtilities setUpUIBenchmark.
-
', Utilities commonRequestStrings contents