// Generated by jextract

package de.hpi.swa.trufflesqueak.interpreterproxy.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class sqVirtualMachine_h extends sqVirtualMachine_h$shared {

    sqVirtualMachine_h() {
        // Should not be called directly
    }

    static Arena libraryArena;

    static SymbolLookup symbolLookup;


    public static void initialize() {
        if (symbolLookup != null) {
            return;
        }
        libraryArena = Arena.ofAuto();
        symbolLookup = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());
        initialize$addresses();
        initialize$constants();
    }


    static void initialize$addresses() {
    }

    static void initialize$constants() {
    }
}

