// Generated by jextract

package bindings.sdl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_GPUTextureCreateInfo {
 *     SDL_GPUTextureType type;
 *     SDL_GPUTextureFormat format;
 *     SDL_GPUTextureUsageFlags usage;
 *     Uint32 width;
 *     Uint32 height;
 *     Uint32 layer_count_or_depth;
 *     Uint32 num_levels;
 *     SDL_GPUSampleCount sample_count;
 *     SDL_PropertiesID props;
 * }
 * }
 */
public class SDL_GPUTextureCreateInfo {

    SDL_GPUTextureCreateInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_INT.withName("type"),
        SDL_h.C_INT.withName("format"),
        SDL_h.C_INT.withName("usage"),
        SDL_h.C_INT.withName("width"),
        SDL_h.C_INT.withName("height"),
        SDL_h.C_INT.withName("layer_count_or_depth"),
        SDL_h.C_INT.withName("num_levels"),
        SDL_h.C_INT.withName("sample_count"),
        SDL_h.C_INT.withName("props")
    ).withName("SDL_GPUTextureCreateInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUTextureType type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUTextureType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUTextureType type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUTextureType type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final OfInt format$LAYOUT = (OfInt)$LAYOUT.select(groupElement("format"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUTextureFormat format
     * }
     */
    public static final OfInt format$layout() {
        return format$LAYOUT;
    }

    private static final long format$OFFSET = $LAYOUT.byteOffset(groupElement("format"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUTextureFormat format
     * }
     */
    public static final long format$offset() {
        return format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUTextureFormat format
     * }
     */
    public static int format(MemorySegment struct) {
        return struct.get(format$LAYOUT, format$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUTextureFormat format
     * }
     */
    public static void format(MemorySegment struct, int fieldValue) {
        struct.set(format$LAYOUT, format$OFFSET, fieldValue);
    }

    private static final OfInt usage$LAYOUT = (OfInt)$LAYOUT.select(groupElement("usage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUTextureUsageFlags usage
     * }
     */
    public static final OfInt usage$layout() {
        return usage$LAYOUT;
    }

    private static final long usage$OFFSET = $LAYOUT.byteOffset(groupElement("usage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUTextureUsageFlags usage
     * }
     */
    public static final long usage$offset() {
        return usage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUTextureUsageFlags usage
     * }
     */
    public static int usage(MemorySegment struct) {
        return struct.get(usage$LAYOUT, usage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUTextureUsageFlags usage
     * }
     */
    public static void usage(MemorySegment struct, int fieldValue) {
        struct.set(usage$LAYOUT, usage$OFFSET, fieldValue);
    }

    private static final OfInt width$LAYOUT = (OfInt)$LAYOUT.select(groupElement("width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 width
     * }
     */
    public static final OfInt width$layout() {
        return width$LAYOUT;
    }

    private static final long width$OFFSET = $LAYOUT.byteOffset(groupElement("width"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 width
     * }
     */
    public static final long width$offset() {
        return width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 width
     * }
     */
    public static int width(MemorySegment struct) {
        return struct.get(width$LAYOUT, width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 width
     * }
     */
    public static void width(MemorySegment struct, int fieldValue) {
        struct.set(width$LAYOUT, width$OFFSET, fieldValue);
    }

    private static final OfInt height$LAYOUT = (OfInt)$LAYOUT.select(groupElement("height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 height
     * }
     */
    public static final OfInt height$layout() {
        return height$LAYOUT;
    }

    private static final long height$OFFSET = $LAYOUT.byteOffset(groupElement("height"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 height
     * }
     */
    public static final long height$offset() {
        return height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 height
     * }
     */
    public static int height(MemorySegment struct) {
        return struct.get(height$LAYOUT, height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 height
     * }
     */
    public static void height(MemorySegment struct, int fieldValue) {
        struct.set(height$LAYOUT, height$OFFSET, fieldValue);
    }

    private static final OfInt layer_count_or_depth$LAYOUT = (OfInt)$LAYOUT.select(groupElement("layer_count_or_depth"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 layer_count_or_depth
     * }
     */
    public static final OfInt layer_count_or_depth$layout() {
        return layer_count_or_depth$LAYOUT;
    }

    private static final long layer_count_or_depth$OFFSET = $LAYOUT.byteOffset(groupElement("layer_count_or_depth"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 layer_count_or_depth
     * }
     */
    public static final long layer_count_or_depth$offset() {
        return layer_count_or_depth$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 layer_count_or_depth
     * }
     */
    public static int layer_count_or_depth(MemorySegment struct) {
        return struct.get(layer_count_or_depth$LAYOUT, layer_count_or_depth$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 layer_count_or_depth
     * }
     */
    public static void layer_count_or_depth(MemorySegment struct, int fieldValue) {
        struct.set(layer_count_or_depth$LAYOUT, layer_count_or_depth$OFFSET, fieldValue);
    }

    private static final OfInt num_levels$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_levels"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 num_levels
     * }
     */
    public static final OfInt num_levels$layout() {
        return num_levels$LAYOUT;
    }

    private static final long num_levels$OFFSET = $LAYOUT.byteOffset(groupElement("num_levels"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 num_levels
     * }
     */
    public static final long num_levels$offset() {
        return num_levels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 num_levels
     * }
     */
    public static int num_levels(MemorySegment struct) {
        return struct.get(num_levels$LAYOUT, num_levels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 num_levels
     * }
     */
    public static void num_levels(MemorySegment struct, int fieldValue) {
        struct.set(num_levels$LAYOUT, num_levels$OFFSET, fieldValue);
    }

    private static final OfInt sample_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sample_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUSampleCount sample_count
     * }
     */
    public static final OfInt sample_count$layout() {
        return sample_count$LAYOUT;
    }

    private static final long sample_count$OFFSET = $LAYOUT.byteOffset(groupElement("sample_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUSampleCount sample_count
     * }
     */
    public static final long sample_count$offset() {
        return sample_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUSampleCount sample_count
     * }
     */
    public static int sample_count(MemorySegment struct) {
        return struct.get(sample_count$LAYOUT, sample_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUSampleCount sample_count
     * }
     */
    public static void sample_count(MemorySegment struct, int fieldValue) {
        struct.set(sample_count$LAYOUT, sample_count$OFFSET, fieldValue);
    }

    private static final OfInt props$LAYOUT = (OfInt)$LAYOUT.select(groupElement("props"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_PropertiesID props
     * }
     */
    public static final OfInt props$layout() {
        return props$LAYOUT;
    }

    private static final long props$OFFSET = $LAYOUT.byteOffset(groupElement("props"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_PropertiesID props
     * }
     */
    public static final long props$offset() {
        return props$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_PropertiesID props
     * }
     */
    public static int props(MemorySegment struct) {
        return struct.get(props$LAYOUT, props$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_PropertiesID props
     * }
     */
    public static void props(MemorySegment struct, int fieldValue) {
        struct.set(props$LAYOUT, props$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

