// Generated by jextract

package bindings.sdl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*SDL_MouseMotionTransformCallback)(void *, Uint64, SDL_Window *, SDL_MouseID, float *, float *)
 * }
 */
public final class SDL_MouseMotionTransformCallback {

    private SDL_MouseMotionTransformCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment userdata, long timestamp, MemorySegment window, int mouseID, MemorySegment x, MemorySegment y);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        SDL_h.C_POINTER,
        SDL_h.C_LONG_LONG,
        SDL_h.C_POINTER,
        SDL_h.C_INT,
        SDL_h.C_POINTER,
        SDL_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = SDL_h.upcallHandle(SDL_MouseMotionTransformCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(SDL_MouseMotionTransformCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment userdata, long timestamp, MemorySegment window, int mouseID, MemorySegment x, MemorySegment y) {
        try {
             DOWN$MH.invokeExact(funcPtr, userdata, timestamp, window, mouseID, x, y);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

