// Generated by jextract

package bindings.sdl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_HapticLeftRight {
 *     SDL_HapticEffectType type;
 *     Uint32 length;
 *     Uint16 large_magnitude;
 *     Uint16 small_magnitude;
 * }
 * }
 */
public class SDL_HapticLeftRight {

    SDL_HapticLeftRight() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_SHORT.withName("type"),
        MemoryLayout.paddingLayout(2),
        SDL_h.C_INT.withName("length"),
        SDL_h.C_SHORT.withName("large_magnitude"),
        SDL_h.C_SHORT.withName("small_magnitude")
    ).withName("SDL_HapticLeftRight");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfShort type$LAYOUT = (OfShort)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_HapticEffectType type
     * }
     */
    public static final OfShort type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_HapticEffectType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_HapticEffectType type
     * }
     */
    public static short type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_HapticEffectType type
     * }
     */
    public static void type(MemorySegment struct, short fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final OfInt length$LAYOUT = (OfInt)$LAYOUT.select(groupElement("length"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 length
     * }
     */
    public static final OfInt length$layout() {
        return length$LAYOUT;
    }

    private static final long length$OFFSET = $LAYOUT.byteOffset(groupElement("length"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 length
     * }
     */
    public static final long length$offset() {
        return length$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 length
     * }
     */
    public static int length(MemorySegment struct) {
        return struct.get(length$LAYOUT, length$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 length
     * }
     */
    public static void length(MemorySegment struct, int fieldValue) {
        struct.set(length$LAYOUT, length$OFFSET, fieldValue);
    }

    private static final OfShort large_magnitude$LAYOUT = (OfShort)$LAYOUT.select(groupElement("large_magnitude"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 large_magnitude
     * }
     */
    public static final OfShort large_magnitude$layout() {
        return large_magnitude$LAYOUT;
    }

    private static final long large_magnitude$OFFSET = $LAYOUT.byteOffset(groupElement("large_magnitude"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 large_magnitude
     * }
     */
    public static final long large_magnitude$offset() {
        return large_magnitude$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 large_magnitude
     * }
     */
    public static short large_magnitude(MemorySegment struct) {
        return struct.get(large_magnitude$LAYOUT, large_magnitude$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 large_magnitude
     * }
     */
    public static void large_magnitude(MemorySegment struct, short fieldValue) {
        struct.set(large_magnitude$LAYOUT, large_magnitude$OFFSET, fieldValue);
    }

    private static final OfShort small_magnitude$LAYOUT = (OfShort)$LAYOUT.select(groupElement("small_magnitude"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 small_magnitude
     * }
     */
    public static final OfShort small_magnitude$layout() {
        return small_magnitude$LAYOUT;
    }

    private static final long small_magnitude$OFFSET = $LAYOUT.byteOffset(groupElement("small_magnitude"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 small_magnitude
     * }
     */
    public static final long small_magnitude$offset() {
        return small_magnitude$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 small_magnitude
     * }
     */
    public static short small_magnitude(MemorySegment struct) {
        return struct.get(small_magnitude$LAYOUT, small_magnitude$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 small_magnitude
     * }
     */
    public static void small_magnitude(MemorySegment struct, short fieldValue) {
        struct.set(small_magnitude$LAYOUT, small_magnitude$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

