// Generated by jextract

package bindings.sdl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_HapticPeriodic {
 *     SDL_HapticEffectType type;
 *     SDL_HapticDirection direction;
 *     Uint32 length;
 *     Uint16 delay;
 *     Uint16 button;
 *     Uint16 interval;
 *     Uint16 period;
 *     Sint16 magnitude;
 *     Sint16 offset;
 *     Uint16 phase;
 *     Uint16 attack_length;
 *     Uint16 attack_level;
 *     Uint16 fade_length;
 *     Uint16 fade_level;
 * }
 * }
 */
public class SDL_HapticPeriodic {

    SDL_HapticPeriodic() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_SHORT.withName("type"),
        MemoryLayout.paddingLayout(2),
        SDL_HapticDirection.layout().withName("direction"),
        SDL_h.C_INT.withName("length"),
        SDL_h.C_SHORT.withName("delay"),
        SDL_h.C_SHORT.withName("button"),
        SDL_h.C_SHORT.withName("interval"),
        SDL_h.C_SHORT.withName("period"),
        SDL_h.C_SHORT.withName("magnitude"),
        SDL_h.C_SHORT.withName("offset"),
        SDL_h.C_SHORT.withName("phase"),
        SDL_h.C_SHORT.withName("attack_length"),
        SDL_h.C_SHORT.withName("attack_level"),
        SDL_h.C_SHORT.withName("fade_length"),
        SDL_h.C_SHORT.withName("fade_level"),
        MemoryLayout.paddingLayout(2)
    ).withName("SDL_HapticPeriodic");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfShort type$LAYOUT = (OfShort)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_HapticEffectType type
     * }
     */
    public static final OfShort type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_HapticEffectType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_HapticEffectType type
     * }
     */
    public static short type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_HapticEffectType type
     * }
     */
    public static void type(MemorySegment struct, short fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final GroupLayout direction$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("direction"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_HapticDirection direction
     * }
     */
    public static final GroupLayout direction$layout() {
        return direction$LAYOUT;
    }

    private static final long direction$OFFSET = $LAYOUT.byteOffset(groupElement("direction"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_HapticDirection direction
     * }
     */
    public static final long direction$offset() {
        return direction$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_HapticDirection direction
     * }
     */
    public static MemorySegment direction(MemorySegment struct) {
        return struct.asSlice(direction$OFFSET, direction$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_HapticDirection direction
     * }
     */
    public static void direction(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, direction$OFFSET, direction$LAYOUT.byteSize());
    }

    private static final OfInt length$LAYOUT = (OfInt)$LAYOUT.select(groupElement("length"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 length
     * }
     */
    public static final OfInt length$layout() {
        return length$LAYOUT;
    }

    private static final long length$OFFSET = $LAYOUT.byteOffset(groupElement("length"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 length
     * }
     */
    public static final long length$offset() {
        return length$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 length
     * }
     */
    public static int length(MemorySegment struct) {
        return struct.get(length$LAYOUT, length$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 length
     * }
     */
    public static void length(MemorySegment struct, int fieldValue) {
        struct.set(length$LAYOUT, length$OFFSET, fieldValue);
    }

    private static final OfShort delay$LAYOUT = (OfShort)$LAYOUT.select(groupElement("delay"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 delay
     * }
     */
    public static final OfShort delay$layout() {
        return delay$LAYOUT;
    }

    private static final long delay$OFFSET = $LAYOUT.byteOffset(groupElement("delay"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 delay
     * }
     */
    public static final long delay$offset() {
        return delay$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 delay
     * }
     */
    public static short delay(MemorySegment struct) {
        return struct.get(delay$LAYOUT, delay$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 delay
     * }
     */
    public static void delay(MemorySegment struct, short fieldValue) {
        struct.set(delay$LAYOUT, delay$OFFSET, fieldValue);
    }

    private static final OfShort button$LAYOUT = (OfShort)$LAYOUT.select(groupElement("button"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 button
     * }
     */
    public static final OfShort button$layout() {
        return button$LAYOUT;
    }

    private static final long button$OFFSET = $LAYOUT.byteOffset(groupElement("button"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 button
     * }
     */
    public static final long button$offset() {
        return button$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 button
     * }
     */
    public static short button(MemorySegment struct) {
        return struct.get(button$LAYOUT, button$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 button
     * }
     */
    public static void button(MemorySegment struct, short fieldValue) {
        struct.set(button$LAYOUT, button$OFFSET, fieldValue);
    }

    private static final OfShort interval$LAYOUT = (OfShort)$LAYOUT.select(groupElement("interval"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 interval
     * }
     */
    public static final OfShort interval$layout() {
        return interval$LAYOUT;
    }

    private static final long interval$OFFSET = $LAYOUT.byteOffset(groupElement("interval"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 interval
     * }
     */
    public static final long interval$offset() {
        return interval$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 interval
     * }
     */
    public static short interval(MemorySegment struct) {
        return struct.get(interval$LAYOUT, interval$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 interval
     * }
     */
    public static void interval(MemorySegment struct, short fieldValue) {
        struct.set(interval$LAYOUT, interval$OFFSET, fieldValue);
    }

    private static final OfShort period$LAYOUT = (OfShort)$LAYOUT.select(groupElement("period"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 period
     * }
     */
    public static final OfShort period$layout() {
        return period$LAYOUT;
    }

    private static final long period$OFFSET = $LAYOUT.byteOffset(groupElement("period"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 period
     * }
     */
    public static final long period$offset() {
        return period$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 period
     * }
     */
    public static short period(MemorySegment struct) {
        return struct.get(period$LAYOUT, period$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 period
     * }
     */
    public static void period(MemorySegment struct, short fieldValue) {
        struct.set(period$LAYOUT, period$OFFSET, fieldValue);
    }

    private static final OfShort magnitude$LAYOUT = (OfShort)$LAYOUT.select(groupElement("magnitude"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Sint16 magnitude
     * }
     */
    public static final OfShort magnitude$layout() {
        return magnitude$LAYOUT;
    }

    private static final long magnitude$OFFSET = $LAYOUT.byteOffset(groupElement("magnitude"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Sint16 magnitude
     * }
     */
    public static final long magnitude$offset() {
        return magnitude$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Sint16 magnitude
     * }
     */
    public static short magnitude(MemorySegment struct) {
        return struct.get(magnitude$LAYOUT, magnitude$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Sint16 magnitude
     * }
     */
    public static void magnitude(MemorySegment struct, short fieldValue) {
        struct.set(magnitude$LAYOUT, magnitude$OFFSET, fieldValue);
    }

    private static final OfShort offset$LAYOUT = (OfShort)$LAYOUT.select(groupElement("offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Sint16 offset
     * }
     */
    public static final OfShort offset$layout() {
        return offset$LAYOUT;
    }

    private static final long offset$OFFSET = $LAYOUT.byteOffset(groupElement("offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Sint16 offset
     * }
     */
    public static final long offset$offset() {
        return offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Sint16 offset
     * }
     */
    public static short offset(MemorySegment struct) {
        return struct.get(offset$LAYOUT, offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Sint16 offset
     * }
     */
    public static void offset(MemorySegment struct, short fieldValue) {
        struct.set(offset$LAYOUT, offset$OFFSET, fieldValue);
    }

    private static final OfShort phase$LAYOUT = (OfShort)$LAYOUT.select(groupElement("phase"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 phase
     * }
     */
    public static final OfShort phase$layout() {
        return phase$LAYOUT;
    }

    private static final long phase$OFFSET = $LAYOUT.byteOffset(groupElement("phase"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 phase
     * }
     */
    public static final long phase$offset() {
        return phase$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 phase
     * }
     */
    public static short phase(MemorySegment struct) {
        return struct.get(phase$LAYOUT, phase$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 phase
     * }
     */
    public static void phase(MemorySegment struct, short fieldValue) {
        struct.set(phase$LAYOUT, phase$OFFSET, fieldValue);
    }

    private static final OfShort attack_length$LAYOUT = (OfShort)$LAYOUT.select(groupElement("attack_length"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 attack_length
     * }
     */
    public static final OfShort attack_length$layout() {
        return attack_length$LAYOUT;
    }

    private static final long attack_length$OFFSET = $LAYOUT.byteOffset(groupElement("attack_length"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 attack_length
     * }
     */
    public static final long attack_length$offset() {
        return attack_length$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 attack_length
     * }
     */
    public static short attack_length(MemorySegment struct) {
        return struct.get(attack_length$LAYOUT, attack_length$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 attack_length
     * }
     */
    public static void attack_length(MemorySegment struct, short fieldValue) {
        struct.set(attack_length$LAYOUT, attack_length$OFFSET, fieldValue);
    }

    private static final OfShort attack_level$LAYOUT = (OfShort)$LAYOUT.select(groupElement("attack_level"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 attack_level
     * }
     */
    public static final OfShort attack_level$layout() {
        return attack_level$LAYOUT;
    }

    private static final long attack_level$OFFSET = $LAYOUT.byteOffset(groupElement("attack_level"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 attack_level
     * }
     */
    public static final long attack_level$offset() {
        return attack_level$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 attack_level
     * }
     */
    public static short attack_level(MemorySegment struct) {
        return struct.get(attack_level$LAYOUT, attack_level$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 attack_level
     * }
     */
    public static void attack_level(MemorySegment struct, short fieldValue) {
        struct.set(attack_level$LAYOUT, attack_level$OFFSET, fieldValue);
    }

    private static final OfShort fade_length$LAYOUT = (OfShort)$LAYOUT.select(groupElement("fade_length"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 fade_length
     * }
     */
    public static final OfShort fade_length$layout() {
        return fade_length$LAYOUT;
    }

    private static final long fade_length$OFFSET = $LAYOUT.byteOffset(groupElement("fade_length"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 fade_length
     * }
     */
    public static final long fade_length$offset() {
        return fade_length$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 fade_length
     * }
     */
    public static short fade_length(MemorySegment struct) {
        return struct.get(fade_length$LAYOUT, fade_length$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 fade_length
     * }
     */
    public static void fade_length(MemorySegment struct, short fieldValue) {
        struct.set(fade_length$LAYOUT, fade_length$OFFSET, fieldValue);
    }

    private static final OfShort fade_level$LAYOUT = (OfShort)$LAYOUT.select(groupElement("fade_level"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint16 fade_level
     * }
     */
    public static final OfShort fade_level$layout() {
        return fade_level$LAYOUT;
    }

    private static final long fade_level$OFFSET = $LAYOUT.byteOffset(groupElement("fade_level"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint16 fade_level
     * }
     */
    public static final long fade_level$offset() {
        return fade_level$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint16 fade_level
     * }
     */
    public static short fade_level(MemorySegment struct) {
        return struct.get(fade_level$LAYOUT, fade_level$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint16 fade_level
     * }
     */
    public static void fade_level(MemorySegment struct, short fieldValue) {
        struct.set(fade_level$LAYOUT, fade_level$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

