// Generated by jextract

package bindings.sdl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_MessageBoxColorScheme {
 *     SDL_MessageBoxColor colors[5];
 * }
 * }
 */
public class SDL_MessageBoxColorScheme {

    SDL_MessageBoxColorScheme() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(5, SDL_MessageBoxColor.layout()).withName("colors")
    ).withName("SDL_MessageBoxColorScheme");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout colors$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("colors"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_MessageBoxColor colors[5]
     * }
     */
    public static final SequenceLayout colors$layout() {
        return colors$LAYOUT;
    }

    private static final long colors$OFFSET = $LAYOUT.byteOffset(groupElement("colors"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_MessageBoxColor colors[5]
     * }
     */
    public static final long colors$offset() {
        return colors$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_MessageBoxColor colors[5]
     * }
     */
    public static MemorySegment colors(MemorySegment struct) {
        return struct.asSlice(colors$OFFSET, colors$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_MessageBoxColor colors[5]
     * }
     */
    public static void colors(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, colors$OFFSET, colors$LAYOUT.byteSize());
    }

    private static long[] colors$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * SDL_MessageBoxColor colors[5]
     * }
     */
    public static long[] colors$dimensions() {
        return colors$DIMS;
    }
    private static final MethodHandle colors$ELEM_HANDLE = colors$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * SDL_MessageBoxColor colors[5]
     * }
     */
    public static MemorySegment colors(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)colors$ELEM_HANDLE.invokeExact(struct, colors$OFFSET, index0);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * SDL_MessageBoxColor colors[5]
     * }
     */
    public static void colors(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, colors(struct, index0), 0L, SDL_MessageBoxColor.layout().byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

