// Generated by jextract

package bindings.sdl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_AssertData {
 *     bool always_ignore;
 *     unsigned int trigger_count;
 *     const char *condition;
 *     const char *filename;
 *     int linenum;
 *     const char *function;
 *     const struct SDL_AssertData *next;
 * }
 * }
 */
public class SDL_AssertData {

    SDL_AssertData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_BOOL.withName("always_ignore"),
        MemoryLayout.paddingLayout(3),
        SDL_h.C_INT.withName("trigger_count"),
        SDL_h.C_POINTER.withName("condition"),
        SDL_h.C_POINTER.withName("filename"),
        SDL_h.C_INT.withName("linenum"),
        MemoryLayout.paddingLayout(4),
        SDL_h.C_POINTER.withName("function"),
        SDL_h.C_POINTER.withName("next")
    ).withName("SDL_AssertData");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfBoolean always_ignore$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("always_ignore"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool always_ignore
     * }
     */
    public static final OfBoolean always_ignore$layout() {
        return always_ignore$LAYOUT;
    }

    private static final long always_ignore$OFFSET = $LAYOUT.byteOffset(groupElement("always_ignore"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool always_ignore
     * }
     */
    public static final long always_ignore$offset() {
        return always_ignore$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool always_ignore
     * }
     */
    public static boolean always_ignore(MemorySegment struct) {
        return struct.get(always_ignore$LAYOUT, always_ignore$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool always_ignore
     * }
     */
    public static void always_ignore(MemorySegment struct, boolean fieldValue) {
        struct.set(always_ignore$LAYOUT, always_ignore$OFFSET, fieldValue);
    }

    private static final OfInt trigger_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("trigger_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int trigger_count
     * }
     */
    public static final OfInt trigger_count$layout() {
        return trigger_count$LAYOUT;
    }

    private static final long trigger_count$OFFSET = $LAYOUT.byteOffset(groupElement("trigger_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int trigger_count
     * }
     */
    public static final long trigger_count$offset() {
        return trigger_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int trigger_count
     * }
     */
    public static int trigger_count(MemorySegment struct) {
        return struct.get(trigger_count$LAYOUT, trigger_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int trigger_count
     * }
     */
    public static void trigger_count(MemorySegment struct, int fieldValue) {
        struct.set(trigger_count$LAYOUT, trigger_count$OFFSET, fieldValue);
    }

    private static final AddressLayout condition$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("condition"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *condition
     * }
     */
    public static final AddressLayout condition$layout() {
        return condition$LAYOUT;
    }

    private static final long condition$OFFSET = $LAYOUT.byteOffset(groupElement("condition"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *condition
     * }
     */
    public static final long condition$offset() {
        return condition$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *condition
     * }
     */
    public static MemorySegment condition(MemorySegment struct) {
        return struct.get(condition$LAYOUT, condition$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *condition
     * }
     */
    public static void condition(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(condition$LAYOUT, condition$OFFSET, fieldValue);
    }

    private static final AddressLayout filename$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("filename"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *filename
     * }
     */
    public static final AddressLayout filename$layout() {
        return filename$LAYOUT;
    }

    private static final long filename$OFFSET = $LAYOUT.byteOffset(groupElement("filename"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *filename
     * }
     */
    public static final long filename$offset() {
        return filename$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *filename
     * }
     */
    public static MemorySegment filename(MemorySegment struct) {
        return struct.get(filename$LAYOUT, filename$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *filename
     * }
     */
    public static void filename(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(filename$LAYOUT, filename$OFFSET, fieldValue);
    }

    private static final OfInt linenum$LAYOUT = (OfInt)$LAYOUT.select(groupElement("linenum"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int linenum
     * }
     */
    public static final OfInt linenum$layout() {
        return linenum$LAYOUT;
    }

    private static final long linenum$OFFSET = $LAYOUT.byteOffset(groupElement("linenum"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int linenum
     * }
     */
    public static final long linenum$offset() {
        return linenum$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int linenum
     * }
     */
    public static int linenum(MemorySegment struct) {
        return struct.get(linenum$LAYOUT, linenum$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int linenum
     * }
     */
    public static void linenum(MemorySegment struct, int fieldValue) {
        struct.set(linenum$LAYOUT, linenum$OFFSET, fieldValue);
    }

    private static final AddressLayout function$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("function"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *function
     * }
     */
    public static final AddressLayout function$layout() {
        return function$LAYOUT;
    }

    private static final long function$OFFSET = $LAYOUT.byteOffset(groupElement("function"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *function
     * }
     */
    public static final long function$offset() {
        return function$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *function
     * }
     */
    public static MemorySegment function(MemorySegment struct) {
        return struct.get(function$LAYOUT, function$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *function
     * }
     */
    public static void function(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(function$LAYOUT, function$OFFSET, fieldValue);
    }

    private static final AddressLayout next$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("next"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct SDL_AssertData *next
     * }
     */
    public static final AddressLayout next$layout() {
        return next$LAYOUT;
    }

    private static final long next$OFFSET = $LAYOUT.byteOffset(groupElement("next"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct SDL_AssertData *next
     * }
     */
    public static final long next$offset() {
        return next$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct SDL_AssertData *next
     * }
     */
    public static MemorySegment next(MemorySegment struct) {
        return struct.get(next$LAYOUT, next$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct SDL_AssertData *next
     * }
     */
    public static void next(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(next$LAYOUT, next$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

