// Generated by jextract

package bindings.sdl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_GPUDepthStencilState {
 *     SDL_GPUCompareOp compare_op;
 *     SDL_GPUStencilOpState back_stencil_state;
 *     SDL_GPUStencilOpState front_stencil_state;
 *     Uint8 compare_mask;
 *     Uint8 write_mask;
 *     bool enable_depth_test;
 *     bool enable_depth_write;
 *     bool enable_stencil_test;
 *     Uint8 padding1;
 *     Uint8 padding2;
 *     Uint8 padding3;
 * }
 * }
 */
public class SDL_GPUDepthStencilState {

    SDL_GPUDepthStencilState() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_INT.withName("compare_op"),
        SDL_GPUStencilOpState.layout().withName("back_stencil_state"),
        SDL_GPUStencilOpState.layout().withName("front_stencil_state"),
        SDL_h.C_CHAR.withName("compare_mask"),
        SDL_h.C_CHAR.withName("write_mask"),
        SDL_h.C_BOOL.withName("enable_depth_test"),
        SDL_h.C_BOOL.withName("enable_depth_write"),
        SDL_h.C_BOOL.withName("enable_stencil_test"),
        SDL_h.C_CHAR.withName("padding1"),
        SDL_h.C_CHAR.withName("padding2"),
        SDL_h.C_CHAR.withName("padding3")
    ).withName("SDL_GPUDepthStencilState");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt compare_op$LAYOUT = (OfInt)$LAYOUT.select(groupElement("compare_op"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUCompareOp compare_op
     * }
     */
    public static final OfInt compare_op$layout() {
        return compare_op$LAYOUT;
    }

    private static final long compare_op$OFFSET = $LAYOUT.byteOffset(groupElement("compare_op"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUCompareOp compare_op
     * }
     */
    public static final long compare_op$offset() {
        return compare_op$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUCompareOp compare_op
     * }
     */
    public static int compare_op(MemorySegment struct) {
        return struct.get(compare_op$LAYOUT, compare_op$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUCompareOp compare_op
     * }
     */
    public static void compare_op(MemorySegment struct, int fieldValue) {
        struct.set(compare_op$LAYOUT, compare_op$OFFSET, fieldValue);
    }

    private static final GroupLayout back_stencil_state$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("back_stencil_state"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOpState back_stencil_state
     * }
     */
    public static final GroupLayout back_stencil_state$layout() {
        return back_stencil_state$LAYOUT;
    }

    private static final long back_stencil_state$OFFSET = $LAYOUT.byteOffset(groupElement("back_stencil_state"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOpState back_stencil_state
     * }
     */
    public static final long back_stencil_state$offset() {
        return back_stencil_state$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOpState back_stencil_state
     * }
     */
    public static MemorySegment back_stencil_state(MemorySegment struct) {
        return struct.asSlice(back_stencil_state$OFFSET, back_stencil_state$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOpState back_stencil_state
     * }
     */
    public static void back_stencil_state(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, back_stencil_state$OFFSET, back_stencil_state$LAYOUT.byteSize());
    }

    private static final GroupLayout front_stencil_state$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("front_stencil_state"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOpState front_stencil_state
     * }
     */
    public static final GroupLayout front_stencil_state$layout() {
        return front_stencil_state$LAYOUT;
    }

    private static final long front_stencil_state$OFFSET = $LAYOUT.byteOffset(groupElement("front_stencil_state"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOpState front_stencil_state
     * }
     */
    public static final long front_stencil_state$offset() {
        return front_stencil_state$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOpState front_stencil_state
     * }
     */
    public static MemorySegment front_stencil_state(MemorySegment struct) {
        return struct.asSlice(front_stencil_state$OFFSET, front_stencil_state$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUStencilOpState front_stencil_state
     * }
     */
    public static void front_stencil_state(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, front_stencil_state$OFFSET, front_stencil_state$LAYOUT.byteSize());
    }

    private static final OfByte compare_mask$LAYOUT = (OfByte)$LAYOUT.select(groupElement("compare_mask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 compare_mask
     * }
     */
    public static final OfByte compare_mask$layout() {
        return compare_mask$LAYOUT;
    }

    private static final long compare_mask$OFFSET = $LAYOUT.byteOffset(groupElement("compare_mask"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 compare_mask
     * }
     */
    public static final long compare_mask$offset() {
        return compare_mask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 compare_mask
     * }
     */
    public static byte compare_mask(MemorySegment struct) {
        return struct.get(compare_mask$LAYOUT, compare_mask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 compare_mask
     * }
     */
    public static void compare_mask(MemorySegment struct, byte fieldValue) {
        struct.set(compare_mask$LAYOUT, compare_mask$OFFSET, fieldValue);
    }

    private static final OfByte write_mask$LAYOUT = (OfByte)$LAYOUT.select(groupElement("write_mask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 write_mask
     * }
     */
    public static final OfByte write_mask$layout() {
        return write_mask$LAYOUT;
    }

    private static final long write_mask$OFFSET = $LAYOUT.byteOffset(groupElement("write_mask"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 write_mask
     * }
     */
    public static final long write_mask$offset() {
        return write_mask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 write_mask
     * }
     */
    public static byte write_mask(MemorySegment struct) {
        return struct.get(write_mask$LAYOUT, write_mask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 write_mask
     * }
     */
    public static void write_mask(MemorySegment struct, byte fieldValue) {
        struct.set(write_mask$LAYOUT, write_mask$OFFSET, fieldValue);
    }

    private static final OfBoolean enable_depth_test$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enable_depth_test"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool enable_depth_test
     * }
     */
    public static final OfBoolean enable_depth_test$layout() {
        return enable_depth_test$LAYOUT;
    }

    private static final long enable_depth_test$OFFSET = $LAYOUT.byteOffset(groupElement("enable_depth_test"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool enable_depth_test
     * }
     */
    public static final long enable_depth_test$offset() {
        return enable_depth_test$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool enable_depth_test
     * }
     */
    public static boolean enable_depth_test(MemorySegment struct) {
        return struct.get(enable_depth_test$LAYOUT, enable_depth_test$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool enable_depth_test
     * }
     */
    public static void enable_depth_test(MemorySegment struct, boolean fieldValue) {
        struct.set(enable_depth_test$LAYOUT, enable_depth_test$OFFSET, fieldValue);
    }

    private static final OfBoolean enable_depth_write$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enable_depth_write"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool enable_depth_write
     * }
     */
    public static final OfBoolean enable_depth_write$layout() {
        return enable_depth_write$LAYOUT;
    }

    private static final long enable_depth_write$OFFSET = $LAYOUT.byteOffset(groupElement("enable_depth_write"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool enable_depth_write
     * }
     */
    public static final long enable_depth_write$offset() {
        return enable_depth_write$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool enable_depth_write
     * }
     */
    public static boolean enable_depth_write(MemorySegment struct) {
        return struct.get(enable_depth_write$LAYOUT, enable_depth_write$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool enable_depth_write
     * }
     */
    public static void enable_depth_write(MemorySegment struct, boolean fieldValue) {
        struct.set(enable_depth_write$LAYOUT, enable_depth_write$OFFSET, fieldValue);
    }

    private static final OfBoolean enable_stencil_test$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enable_stencil_test"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool enable_stencil_test
     * }
     */
    public static final OfBoolean enable_stencil_test$layout() {
        return enable_stencil_test$LAYOUT;
    }

    private static final long enable_stencil_test$OFFSET = $LAYOUT.byteOffset(groupElement("enable_stencil_test"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool enable_stencil_test
     * }
     */
    public static final long enable_stencil_test$offset() {
        return enable_stencil_test$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool enable_stencil_test
     * }
     */
    public static boolean enable_stencil_test(MemorySegment struct) {
        return struct.get(enable_stencil_test$LAYOUT, enable_stencil_test$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool enable_stencil_test
     * }
     */
    public static void enable_stencil_test(MemorySegment struct, boolean fieldValue) {
        struct.set(enable_stencil_test$LAYOUT, enable_stencil_test$OFFSET, fieldValue);
    }

    private static final OfByte padding1$LAYOUT = (OfByte)$LAYOUT.select(groupElement("padding1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static final OfByte padding1$layout() {
        return padding1$LAYOUT;
    }

    private static final long padding1$OFFSET = $LAYOUT.byteOffset(groupElement("padding1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static final long padding1$offset() {
        return padding1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static byte padding1(MemorySegment struct) {
        return struct.get(padding1$LAYOUT, padding1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 padding1
     * }
     */
    public static void padding1(MemorySegment struct, byte fieldValue) {
        struct.set(padding1$LAYOUT, padding1$OFFSET, fieldValue);
    }

    private static final OfByte padding2$LAYOUT = (OfByte)$LAYOUT.select(groupElement("padding2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static final OfByte padding2$layout() {
        return padding2$LAYOUT;
    }

    private static final long padding2$OFFSET = $LAYOUT.byteOffset(groupElement("padding2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static final long padding2$offset() {
        return padding2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static byte padding2(MemorySegment struct) {
        return struct.get(padding2$LAYOUT, padding2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 padding2
     * }
     */
    public static void padding2(MemorySegment struct, byte fieldValue) {
        struct.set(padding2$LAYOUT, padding2$OFFSET, fieldValue);
    }

    private static final OfByte padding3$LAYOUT = (OfByte)$LAYOUT.select(groupElement("padding3"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static final OfByte padding3$layout() {
        return padding3$LAYOUT;
    }

    private static final long padding3$OFFSET = $LAYOUT.byteOffset(groupElement("padding3"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static final long padding3$offset() {
        return padding3$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static byte padding3(MemorySegment struct) {
        return struct.get(padding3$LAYOUT, padding3$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint8 padding3
     * }
     */
    public static void padding3(MemorySegment struct, byte fieldValue) {
        struct.set(padding3$LAYOUT, padding3$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

