// Generated by jextract

package bindings.sdl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_CameraSpec {
 *     SDL_PixelFormat format;
 *     SDL_Colorspace colorspace;
 *     int width;
 *     int height;
 *     int framerate_numerator;
 *     int framerate_denominator;
 * }
 * }
 */
public class SDL_CameraSpec {

    SDL_CameraSpec() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_INT.withName("format"),
        SDL_h.C_INT.withName("colorspace"),
        SDL_h.C_INT.withName("width"),
        SDL_h.C_INT.withName("height"),
        SDL_h.C_INT.withName("framerate_numerator"),
        SDL_h.C_INT.withName("framerate_denominator")
    ).withName("SDL_CameraSpec");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt format$LAYOUT = (OfInt)$LAYOUT.select(groupElement("format"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_PixelFormat format
     * }
     */
    public static final OfInt format$layout() {
        return format$LAYOUT;
    }

    private static final long format$OFFSET = $LAYOUT.byteOffset(groupElement("format"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_PixelFormat format
     * }
     */
    public static final long format$offset() {
        return format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_PixelFormat format
     * }
     */
    public static int format(MemorySegment struct) {
        return struct.get(format$LAYOUT, format$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_PixelFormat format
     * }
     */
    public static void format(MemorySegment struct, int fieldValue) {
        struct.set(format$LAYOUT, format$OFFSET, fieldValue);
    }

    private static final OfInt colorspace$LAYOUT = (OfInt)$LAYOUT.select(groupElement("colorspace"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_Colorspace colorspace
     * }
     */
    public static final OfInt colorspace$layout() {
        return colorspace$LAYOUT;
    }

    private static final long colorspace$OFFSET = $LAYOUT.byteOffset(groupElement("colorspace"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_Colorspace colorspace
     * }
     */
    public static final long colorspace$offset() {
        return colorspace$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_Colorspace colorspace
     * }
     */
    public static int colorspace(MemorySegment struct) {
        return struct.get(colorspace$LAYOUT, colorspace$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_Colorspace colorspace
     * }
     */
    public static void colorspace(MemorySegment struct, int fieldValue) {
        struct.set(colorspace$LAYOUT, colorspace$OFFSET, fieldValue);
    }

    private static final OfInt width$LAYOUT = (OfInt)$LAYOUT.select(groupElement("width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static final OfInt width$layout() {
        return width$LAYOUT;
    }

    private static final long width$OFFSET = $LAYOUT.byteOffset(groupElement("width"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static final long width$offset() {
        return width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static int width(MemorySegment struct) {
        return struct.get(width$LAYOUT, width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static void width(MemorySegment struct, int fieldValue) {
        struct.set(width$LAYOUT, width$OFFSET, fieldValue);
    }

    private static final OfInt height$LAYOUT = (OfInt)$LAYOUT.select(groupElement("height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static final OfInt height$layout() {
        return height$LAYOUT;
    }

    private static final long height$OFFSET = $LAYOUT.byteOffset(groupElement("height"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static final long height$offset() {
        return height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static int height(MemorySegment struct) {
        return struct.get(height$LAYOUT, height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static void height(MemorySegment struct, int fieldValue) {
        struct.set(height$LAYOUT, height$OFFSET, fieldValue);
    }

    private static final OfInt framerate_numerator$LAYOUT = (OfInt)$LAYOUT.select(groupElement("framerate_numerator"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int framerate_numerator
     * }
     */
    public static final OfInt framerate_numerator$layout() {
        return framerate_numerator$LAYOUT;
    }

    private static final long framerate_numerator$OFFSET = $LAYOUT.byteOffset(groupElement("framerate_numerator"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int framerate_numerator
     * }
     */
    public static final long framerate_numerator$offset() {
        return framerate_numerator$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int framerate_numerator
     * }
     */
    public static int framerate_numerator(MemorySegment struct) {
        return struct.get(framerate_numerator$LAYOUT, framerate_numerator$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int framerate_numerator
     * }
     */
    public static void framerate_numerator(MemorySegment struct, int fieldValue) {
        struct.set(framerate_numerator$LAYOUT, framerate_numerator$OFFSET, fieldValue);
    }

    private static final OfInt framerate_denominator$LAYOUT = (OfInt)$LAYOUT.select(groupElement("framerate_denominator"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int framerate_denominator
     * }
     */
    public static final OfInt framerate_denominator$layout() {
        return framerate_denominator$LAYOUT;
    }

    private static final long framerate_denominator$OFFSET = $LAYOUT.byteOffset(groupElement("framerate_denominator"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int framerate_denominator
     * }
     */
    public static final long framerate_denominator$offset() {
        return framerate_denominator$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int framerate_denominator
     * }
     */
    public static int framerate_denominator(MemorySegment struct) {
        return struct.get(framerate_denominator$LAYOUT, framerate_denominator$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int framerate_denominator
     * }
     */
    public static void framerate_denominator(MemorySegment struct, int fieldValue) {
        struct.set(framerate_denominator$LAYOUT, framerate_denominator$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

