// Generated by jextract

package bindings.sdl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_GPUIndirectDrawCommand {
 *     Uint32 num_vertices;
 *     Uint32 num_instances;
 *     Uint32 first_vertex;
 *     Uint32 first_instance;
 * }
 * }
 */
public class SDL_GPUIndirectDrawCommand {

    SDL_GPUIndirectDrawCommand() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_INT.withName("num_vertices"),
        SDL_h.C_INT.withName("num_instances"),
        SDL_h.C_INT.withName("first_vertex"),
        SDL_h.C_INT.withName("first_instance")
    ).withName("SDL_GPUIndirectDrawCommand");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt num_vertices$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_vertices"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 num_vertices
     * }
     */
    public static final OfInt num_vertices$layout() {
        return num_vertices$LAYOUT;
    }

    private static final long num_vertices$OFFSET = $LAYOUT.byteOffset(groupElement("num_vertices"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 num_vertices
     * }
     */
    public static final long num_vertices$offset() {
        return num_vertices$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 num_vertices
     * }
     */
    public static int num_vertices(MemorySegment struct) {
        return struct.get(num_vertices$LAYOUT, num_vertices$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 num_vertices
     * }
     */
    public static void num_vertices(MemorySegment struct, int fieldValue) {
        struct.set(num_vertices$LAYOUT, num_vertices$OFFSET, fieldValue);
    }

    private static final OfInt num_instances$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_instances"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 num_instances
     * }
     */
    public static final OfInt num_instances$layout() {
        return num_instances$LAYOUT;
    }

    private static final long num_instances$OFFSET = $LAYOUT.byteOffset(groupElement("num_instances"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 num_instances
     * }
     */
    public static final long num_instances$offset() {
        return num_instances$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 num_instances
     * }
     */
    public static int num_instances(MemorySegment struct) {
        return struct.get(num_instances$LAYOUT, num_instances$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 num_instances
     * }
     */
    public static void num_instances(MemorySegment struct, int fieldValue) {
        struct.set(num_instances$LAYOUT, num_instances$OFFSET, fieldValue);
    }

    private static final OfInt first_vertex$LAYOUT = (OfInt)$LAYOUT.select(groupElement("first_vertex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 first_vertex
     * }
     */
    public static final OfInt first_vertex$layout() {
        return first_vertex$LAYOUT;
    }

    private static final long first_vertex$OFFSET = $LAYOUT.byteOffset(groupElement("first_vertex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 first_vertex
     * }
     */
    public static final long first_vertex$offset() {
        return first_vertex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 first_vertex
     * }
     */
    public static int first_vertex(MemorySegment struct) {
        return struct.get(first_vertex$LAYOUT, first_vertex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 first_vertex
     * }
     */
    public static void first_vertex(MemorySegment struct, int fieldValue) {
        struct.set(first_vertex$LAYOUT, first_vertex$OFFSET, fieldValue);
    }

    private static final OfInt first_instance$LAYOUT = (OfInt)$LAYOUT.select(groupElement("first_instance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 first_instance
     * }
     */
    public static final OfInt first_instance$layout() {
        return first_instance$LAYOUT;
    }

    private static final long first_instance$OFFSET = $LAYOUT.byteOffset(groupElement("first_instance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 first_instance
     * }
     */
    public static final long first_instance$offset() {
        return first_instance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 first_instance
     * }
     */
    public static int first_instance(MemorySegment struct) {
        return struct.get(first_instance$LAYOUT, first_instance$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 first_instance
     * }
     */
    public static void first_instance(MemorySegment struct, int fieldValue) {
        struct.set(first_instance$LAYOUT, first_instance$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

