// Generated by jextract

package bindings.sdl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef SDL_EGLint *(*SDL_EGLIntArrayCallback)(void *, SDL_EGLDisplay, SDL_EGLConfig)
 * }
 */
public final class SDL_EGLIntArrayCallback {

    private SDL_EGLIntArrayCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        MemorySegment apply(MemorySegment userdata, MemorySegment display, MemorySegment config);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        SDL_h.C_POINTER,
        SDL_h.C_POINTER,
        SDL_h.C_POINTER,
        SDL_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = SDL_h.upcallHandle(SDL_EGLIntArrayCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(SDL_EGLIntArrayCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static MemorySegment invoke(MemorySegment funcPtr, MemorySegment userdata, MemorySegment display, MemorySegment config) {
        try {
            return (MemorySegment) DOWN$MH.invokeExact(funcPtr, userdata, display, config);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

