// Generated by jextract

package bindings.sdl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SDL_GPUVertexAttribute {
 *     Uint32 location;
 *     Uint32 buffer_slot;
 *     SDL_GPUVertexElementFormat format;
 *     Uint32 offset;
 * }
 * }
 */
public class SDL_GPUVertexAttribute {

    SDL_GPUVertexAttribute() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SDL_h.C_INT.withName("location"),
        SDL_h.C_INT.withName("buffer_slot"),
        SDL_h.C_INT.withName("format"),
        SDL_h.C_INT.withName("offset")
    ).withName("SDL_GPUVertexAttribute");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt location$LAYOUT = (OfInt)$LAYOUT.select(groupElement("location"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 location
     * }
     */
    public static final OfInt location$layout() {
        return location$LAYOUT;
    }

    private static final long location$OFFSET = $LAYOUT.byteOffset(groupElement("location"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 location
     * }
     */
    public static final long location$offset() {
        return location$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 location
     * }
     */
    public static int location(MemorySegment struct) {
        return struct.get(location$LAYOUT, location$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 location
     * }
     */
    public static void location(MemorySegment struct, int fieldValue) {
        struct.set(location$LAYOUT, location$OFFSET, fieldValue);
    }

    private static final OfInt buffer_slot$LAYOUT = (OfInt)$LAYOUT.select(groupElement("buffer_slot"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 buffer_slot
     * }
     */
    public static final OfInt buffer_slot$layout() {
        return buffer_slot$LAYOUT;
    }

    private static final long buffer_slot$OFFSET = $LAYOUT.byteOffset(groupElement("buffer_slot"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 buffer_slot
     * }
     */
    public static final long buffer_slot$offset() {
        return buffer_slot$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 buffer_slot
     * }
     */
    public static int buffer_slot(MemorySegment struct) {
        return struct.get(buffer_slot$LAYOUT, buffer_slot$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 buffer_slot
     * }
     */
    public static void buffer_slot(MemorySegment struct, int fieldValue) {
        struct.set(buffer_slot$LAYOUT, buffer_slot$OFFSET, fieldValue);
    }

    private static final OfInt format$LAYOUT = (OfInt)$LAYOUT.select(groupElement("format"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SDL_GPUVertexElementFormat format
     * }
     */
    public static final OfInt format$layout() {
        return format$LAYOUT;
    }

    private static final long format$OFFSET = $LAYOUT.byteOffset(groupElement("format"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SDL_GPUVertexElementFormat format
     * }
     */
    public static final long format$offset() {
        return format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SDL_GPUVertexElementFormat format
     * }
     */
    public static int format(MemorySegment struct) {
        return struct.get(format$LAYOUT, format$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SDL_GPUVertexElementFormat format
     * }
     */
    public static void format(MemorySegment struct, int fieldValue) {
        struct.set(format$LAYOUT, format$OFFSET, fieldValue);
    }

    private static final OfInt offset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Uint32 offset
     * }
     */
    public static final OfInt offset$layout() {
        return offset$LAYOUT;
    }

    private static final long offset$OFFSET = $LAYOUT.byteOffset(groupElement("offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Uint32 offset
     * }
     */
    public static final long offset$offset() {
        return offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Uint32 offset
     * }
     */
    public static int offset(MemorySegment struct) {
        return struct.get(offset$LAYOUT, offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Uint32 offset
     * }
     */
    public static void offset(MemorySegment struct, int fieldValue) {
        struct.set(offset$LAYOUT, offset$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

