# This file contains native-image arguments needed to build TruffleSqueak
#

Requires = language:nfi

Args = --initialize-at-build-time=de.hpi.swa.trufflesqueak \
       --initialize-at-run-time=de.hpi.swa.trufflesqueak.sdl3.bindings \
       --add-exports=java.base/jdk.internal.module=de.hpi.swa.trufflesqueak \
       -H:MaxRuntimeCompileMethods=5000 \
       --link-at-build-time \
       -Dorg.graalvm.launcher.relative.smalltalk.home\=.. \
